- saga-core/src/main/java/io/servicecomb/saga/core/EmbeddedEventStore.java
method `description` has already implemented the functionality of `getClass().getSimpleName()`, just call the class method directly.
> JAV-227 use class method instead of detail implementation

- saga-core/src/main/java/io/servicecomb/saga/core/BackwardRecovery.java
- saga-core/src/main/java/io/servicecomb/saga/core/ForwardRecovery.java
- saga-core/src/main/java/io/servicecomb/saga/core/LoggingRecoveryPolicy.java
- saga-core/src/main/java/io/servicecomb/saga/core/NoOpSagaRequest.java
- saga-core/src/main/java/io/servicecomb/saga/core/RecoveryPolicy.java
- saga-core/src/main/java/io/servicecomb/saga/core/SagaRequest.java
- saga-core/src/main/java/io/servicecomb/saga/core/SagaRequestImpl.java
- saga-core/src/test/java/io/servicecomb/saga/core/ForwardRecoveryTest.java
- saga-format/src/main/java/io/servicecomb/saga/format/JsonRestSagaRequest.java
- saga-format/src/test/java/io/servicecomb/saga/format/JsonRestSagaRequestTest.java
最大变更是修改了RecoveryPolicy接口的apply方法由void返回为retryCount，用于单元测试；
虽然有别的方式，但是觉得不好看，retryCount下一个阶段会有用，例如需要扩展ForwardRecovery不能无限重试，可以设置重试次数，然后做检查。
> Jav 370 forward recovery delay

- saga-spring/src/main/resources/schema-mysql.sql
Original content：
`creation_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
Modified content：
`creation_time` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
This operation is to solve this problem https://github.com/ServiceComb/ServiceComb-Saga/issues/68
> Modify the DDL statement

- .travis.yml
- alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/GrpcTxEventEndpointImpl.java
- alpha/alpha-server/src/test/java/org/apache/servicecomb/saga/alpha/server/AlphaIntegrationTest.java
- omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/GrpcClientMessageSender.java
- omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/GrpcCompensateStreamObserver.java
- omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSender.java
- omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/PushBackReconnectRunnable.java
- omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSenderTest.java
- omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/PushBackReconnectRunnableTest.java
- omega/omega-spring-starter/src/main/java/org/apache/servicecomb/saga/omega/spring/OmegaSpringConfig.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/MessageSender.java
> [SCB-164] reconnect on crash

- alpha/alpha-core/src/main/java/org/apache/servicecomb/saga/alpha/core/TxConsistentService.java
- alpha/alpha-core/src/test/java/org/apache/servicecomb/saga/alpha/core/TxConsistentServiceTest.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/TransactionAspect.java
> SCB-213 proper timing to handle SagaEndedEvent in asynchronous situation

- README.md
- README_ZH.md
- docs/user_guide.md
- docs/user_guide_zh.md
> SCB-395 add guides to build executable files

- acceptance-tests/acceptance-pack/src/test/java/org/apache/servicecomb/saga/PackStepdefs.java
- acceptance-tests/acceptance-pack/src/test/resources/booking_timeout.btm
- acceptance-tests/acceptance-pack/src/test/resources/pack_timeout_scenario.feature
- saga-demo/booking/booking/src/main/java/org/apache/servicecomb/saga/demo/pack/booking/BookingController.java
> [SCB-300] acceptance test of the timeout

- alpha/README.md
- saga-demo/booking/README.md
Add document on alpha-server and link it to saga-demo document.
Add the README.me file under `alpha/`, describe how to build and run alpha-server, and add links to alpha-server in saga demo's document, making alpha-server as a prerequisite.
I add this because I failed to notice that alpha-server is needed to run saga demo at my first try.
> Add guide on how to build and run alpha server

- omega/omega-transport/omega-transport-dubbo/src/test/java/SagaDubboConsumerFilterTest.java
- omega/omega-transport/omega-transport-dubbo/src/test/java/SagaDubboProviderFilterTest.java
The IdGenerator is not used thus removed.
Also add omegaContext.clear() in setup to make the tests pass
in linux. But the problem still exists, the filters should use
a better way to get the omegaContext, see SCB-584 for details.
---
> [SCB-584] Clear up testing code for Dubbo filter tests

- omega/omega-transport/omega-transport-feign/pom.xml
- omega/omega-transport/omega-transport-feign/src/main/java/org/apache/servicecomb/saga/omega/transport/feign/FeignAutoConfiguration.java
- omega/omega-transport/omega-transport-feign/src/main/java/org/apache/servicecomb/saga/omega/transport/feign/FeignClientRequestInterceptor.java
- omega/omega-transport/omega-transport-feign/src/main/resources/META-INF/spring.factories
- omega/omega-transport/omega-transport-feign/src/test/java/org/apache/servicecomb/saga/omega/transport/feign/FeignAutoConfigurationTest.java
- omega/omega-transport/pom.xml
满足spring cloud下服务间使用openfeign进行服务间通讯使用saga实现分布式事务。实现feign接口调用过程中传递全局事ID和本地事务ID传递。
奉献绵薄之力，经过测试，目前已经可以完整对接feign。
---
> SCB-730 Add Feign transport for supporting Spring Cloud

- alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/GrpcTxEventEndpointImpl.java
If the node time of alpha and omega are not same, the transaction could be aborted.
As the alpha just create the TxEvent which is based on the omega's message timestamp, it could trigger the EventScanner timeout check to abort the transaction. We should use the Alpha timestamp to create the date.
直接使用收到TxEvent的时间作为TxEvent的创建时间，以避免omega与alpha的时间不同步，分布式事务被意外aborted
1. 直接使用收到TxEvent的时间作为TxEvent的创建时间，以避免omega与alpha的时间不同步，分布式事务被意外aborted
- [ x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in …
> [SCB-805] If the node time of alpha and omega are not same, the transaction could be aborted

- acceptance-tests/acceptance-pack-dubbo-demo/src/test/resources/AExceptionWhenAb_scenario.feature
- acceptance-tests/acceptance-pack-dubbo-demo/src/test/resources/BExceptionWhenAb_scenario.feature
- acceptance-tests/acceptance-pack-dubbo-demo/src/test/resources/CExceptionWhenAbAc_scenario.feature
- acceptance-tests/acceptance-pack-dubbo-demo/src/test/resources/CExceptionWhenAbBc_scenario.feature
- acceptance-tests/acceptance-pack-spring-demo/src/test/java/org/apache/servicecomb/saga/PackStepdefs.java
- acceptance-tests/acceptance-pack-spring-demo/src/test/resources/booking_exception.btm
- acceptance-tests/acceptance-pack-spring-demo/src/test/resources/pack_compensation_scenario.feature
- acceptance-tests/acceptance-pack-spring-demo/src/test/resources/pack_post_car_exception_scenario.feature
- alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/AlphaEventController.java
- integration-tests/pack-tests/src/test/java/org/apache/servicecomb/saga/integration/pack/tests/PackIT.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAspect.java
- omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAspectTest.java
- saga-demo/saga-spring-demo/booking/src/main/java/org/apache/servicecomb/saga/demo/pack/booking/BookingController.java
This TxAbortEvent doesn't have the parent transaction Id, and it's global transaction id and local transaction id is same.
> SCB-784 SagaStart should send TxAbortEvent when the exception is thrown

- pom.xml
1. 升级依赖的protoc-gen-grpc-java版本，见 https://github.com/grpc/grpc-java/issues/1683
- [ x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ x ] Each commit in the pull request should have a meaningful subject line and body.
- [ x ] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
- [ x ] Write a pull request description that is detailed enough to understand what the pull request does, …
> [SCB-813] Fix the pack-contract-grpc build issue on macOSX

- omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSender.java
- omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/MessageSenderPicker.java
The first part of SCB-745, refactoring LoadBalancedClusterMessageSender, allowing customizing the strategy of MessageSender choosing.
> [SCB-745] (WIP)RetrySender should not throw exception when go the saga start event

- omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/AlphaClusterConfig.java
- omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSender.java
- omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalanceClusterMessageSenderWithTLSTest.java
- omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSenderTest.java
- omega/omega-spring-starter/src/main/java/org/apache/servicecomb/saga/omega/spring/OmegaSpringConfig.java
- Extending AlphaClusterConfig by adding MessageHandler, MessageSerializer and MessageDeserializer property.
- Refactoring the constructor of LoadBalancedClusterMessageSender.
- Modifying respective test cases and references.
- Killing some issue detected by SonarLint.
> [SCB-745] Applying Builder Pattern on AlphaClusterConfig.

- saga-core/src/main/java/org/apache/servicecomb/saga/core/SQLOperation.java
- saga-core/src/main/java/org/apache/servicecomb/saga/transports/SQLTransport.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonSQLCompensation.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonSQLOperation.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonSQLTransaction.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JsonSQLSagaRequest.java
- saga-format/src/test/java/org/apache/servicecomb/saga/format/JacksonFromJsonFormatForSQLTest.java
- saga-format/src/test/java/org/apache/servicecomb/saga/format/JsonSQLSagaRequestTest.java
Add SQLTransport in saga-core and add JacksonSQLFormat in saga-format
> [SCB-864] Add SQLTransport and JacksonSQLFormat

- omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/EventAwareInterceptor.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/NoOpEventAwareInterceptor.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAnnotationProcessor.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAspect.java
- omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAnnotationProcessorTest.java
1.Remove the inheritance hierarchy between SagaStartAnnotationProcessor and EventAwareInterceptor.
2.Remove the NO_OP_INTERCEPTOR from the interface EventAwareInterceptor. Turning the NoOp Implementation into a class of static singleton pattern.
3.Removing parentId when dealing with error.
> [SCB-865] Refactoring the Omega Interceptors

- omega/omega-connector/omega-connector-grpc/pom.xml
- omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/GrpcCoordinateStreamObserver.java
- omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/GrpcTccEventService.java
- omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/GrpcTccEventServiceTest.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/tcc/CoordinateMessageHandler.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/tcc/MessageHandler.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/tcc/TccStartAnnotationProcessor.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/tcc/events/CoordinatedEvent.java
- omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/tcc/CoordinateMessageHandlerTest.java
- omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/tcc/TccParticipatorAspectTest.java
- omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/tcc/TccStartAnnotationProcessorTest.java
- omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/tcc/TccStartAspectTest.java
- pack-contracts/pack-contract-grpc/src/main/proto/GrpcTccEvent.proto
- pom.xml
* Updated the TCC protocol for CoordinatedEvent
* Update the omega transactions code
* Implemented the TccEventServie of grpc
> SCB-817, SCB-818  TCC Omega side implemenation

- docs/api/api.md
- saga-core/src/main/java/org/apache/servicecomb/saga/core/SQLOperation.java
- saga-core/src/main/java/org/apache/servicecomb/saga/transports/SQLTransport.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonSQLCompensation.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonSQLOperation.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonSQLTransaction.java
- saga-format/src/test/java/org/apache/servicecomb/saga/format/JacksonFromJsonFormatForSQLTest.java
> [SCB-864] support multiple parameters for each sql

- docs/api/api.md
- saga-core-akka/src/test/java/org/apache/servicecomb/saga/core/actors/ActorBasedSagaIntegrationTest.java
- saga-core/src/main/java/org/apache/servicecomb/saga/core/Compensation.java
- saga-core/src/main/java/org/apache/servicecomb/saga/core/Fallback.java
- saga-core/src/main/java/org/apache/servicecomb/saga/core/ForwardRecovery.java
- saga-core/src/main/java/org/apache/servicecomb/saga/core/GraphBasedSaga.java
- saga-core/src/main/java/org/apache/servicecomb/saga/core/Operation.java
- saga-core/src/main/java/org/apache/servicecomb/saga/core/RestOperation.java
- saga-core/src/main/java/org/apache/servicecomb/saga/core/SQLOperation.java
- saga-core/src/main/java/org/apache/servicecomb/saga/core/Transaction.java
- saga-core/src/main/java/org/apache/servicecomb/saga/core/TransactionAbortedException.java
- saga-core/src/main/java/org/apache/servicecomb/saga/core/TransactionTaskConsumer.java
- saga-core/src/test/java/org/apache/servicecomb/saga/core/ForwardRecoveryTest.java
- saga-core/src/test/java/org/apache/servicecomb/saga/core/SagaIntegrationTest.java
- saga-core/src/test/java/org/apache/servicecomb/saga/core/TransactionImpl.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonFallback.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonRestCompensation.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonRestFallback.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonRestOperation.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonRestTransaction.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonSQLOperation.java
- saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonSQLTransaction.java
- saga-format/src/test/java/org/apache/servicecomb/saga/format/JacksonFromJsonFormatForSQLTest.java
Support ForwardPolicy to configure the maximum of retries
> [SCB-962] Support ForwardPolicy to configure the maximum of retries

- alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/AlphaConfig.java
Now we can only start one event scanner, it makes sense that we can disable by using the configuration.
> SCB-1013 Support to disable the event scanner of Alpha

- alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/TxEventEnvelopeRepository.java
- alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/console/saga/SagaTransactionsController.java
- alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/console/saga/model/Stats.java
This set of API's has been implemented to expose the saga events through API's which can be used by Saga Dashboard.
---
> SCB-995 Implement Saga Console API's

- omega/omega-spring-tx/src/test/java/org/apache/servicecomb/saga/omega/transaction/spring/CompensableAnnotationCheckingTest.java
- omega/omega-spring-tx/src/test/java/org/apache/servicecomb/saga/omega/transaction/spring/MisconfiguredRetriesService.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/annotations/Compensable.java
Now we will check the compensable retries setting first to avoid the situation of setting below -1.
> SCB-1039 Add a check for the compensable retries setting

- alpha/alpha-core/src/main/java/org/apache/servicecomb/pack/alpha/core/EventScanner.java
Catching the EventScanner.polleEvents() exception To fix the issue of #382.
> SCB-1118 Catch the exception to keep EventScanner running

- alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/AlphaIntegrationTest.java
class AlphaIntegrationTest method abortTimeoutTxStartedEvent defects
```
await().atMost(2, SECONDS).until(() -> {
List<TxEvent> events = eventRepo.findByGlobalTxId(globalTxId);
return eventRepo.count() == 5 && events.get(events.size() - 1).type().equals(SagaEndedEvent.name());
});
```
Sometimes although eventRepo.count()==5 but there events list of results as follows
```
SagaStartedEvent
TxStartedEvent
TxAbortedEvent
SagaEndedEvent
SagaEndedEvent
```
compensation has not yet executed a cycle (method deleteDuplicateSagaEndedEvents() has not been executed yet), TxCompensatedEvent has not been added yet, but the condition eventRepo.count()==5 is met, so I changed to the following
```
await().atMost(2, SECONDS).until(() -> {
List<TxEvent> events = eventRepo.findByGlobalTxId(globalTxId); …
```
> [SCB-1152] Fixed test case logic to determine defects

- README.md
- README_ZH.md
- acceptance-tests/acceptance-pack-cluster-spring-demo/pom.xml
- acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/java/org/apache/servicecomb/pack/PackStepdefs.java
- acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/java/org/apache/servicecomb/pack/RunCucumberIT.java
- acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/alpha_shutdown.btm
- acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/booking_exception.btm
- acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/booking_timeout.btm
- acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/log4j2-test.xml
- acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/pack_compensation_scenario.feature
- acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/pack_post_car_exception_scenario.feature
- acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/pack_success_scenario.feature
- acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/pack_timeout_scenario.feature
- acceptance-tests/pom.xml
- alpha/alpha-core/src/main/java/org/apache/servicecomb/pack/alpha/core/actuate/endpoint/AlphaStatus.java
- alpha/alpha-server/pom.xml
- alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/cluster/master/ClusterLockService.java
- alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/cluster/master/ClusterLockServiceTest.java
- alpha/alpha-spring-boot-compatibility/alpha-spring-boot-1-starter/pom.xml
- alpha/alpha-spring-boot-compatibility/alpha-spring-boot-1-starter/src/main/java/org/apache/servicecomb/pack/alpha/server/actuate/endpoint/ActuatorEndpoint.java
- alpha/alpha-spring-boot-compatibility/alpha-spring-boot-1-starter/src/main/java/org/apache/servicecomb/pack/alpha/server/actuate/endpoint/AlphaEndpoint.java
- alpha/alpha-spring-boot-compatibility/alpha-spring-boot-1-starter/src/main/java/org/apache/servicecomb/pack/alpha/server/actuate/endpoint/mvc/ActuatorMvcEndpoint.java
- alpha/alpha-spring-boot-compatibility/alpha-spring-boot-2-starter/pom.xml
- alpha/alpha-spring-boot-compatibility/alpha-spring-boot-2-starter/src/main/java/org/apache/servicecomb/pack/alpha/server/actuate/endpoint/AlphaEndPoint.java
- alpha/alpha-spring-boot-compatibility/pom.xml
- demo/saga-spring-demo/booking/src/main/java/org/apache/servicecomb/pack/demo/booking/BookingController.java
- docs/faq/cn/how_to_use_mysql_as_alpha_backend_database.md
- docs/faq/en/how_to_use_mysql_as_alpha_backend_database.md
- docs/user_guide.md
- docs/user_guide_zh.md
We can use loads external jars support multiple database types
create libs directory in the alpha-server-0.4.0-SNAPSHOT-exec.jar directory, copy mysql-connector-java-8.0.15.jar to the libs directory And add config -Dloader.path=./libs to the command line, e.g.
```shell
java -Dloader.path=./libs -jar alpha-server-0.4.0-SNAPSHOT-exec.jar \
--spring.datasource.platform=mysql \
--spring.datasource.dataSourceClassName=com.mysql.jdbc.Driver \
--spring.datasource.url='jdbc:mysql://0.0.0.0:3306/saga?useUnicode=true&characterEncoding=utf-8&autoReconnect=true' \
--spring.datasource.username=saga-user \
--spring.datasource.password=saga-password \
--spring.profiles.active=prd
```
In order to external jars support need to modify alpha-server pom.xml use `ZIP` layout in maven plugin configuration, e.g …
> [SCB-1158] Modify `ZIP` layout in maven plugin configuration support external jars

- alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/AlphaConfig.java
- alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/GrpcServerConfig.java
- alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/GrpcStartable.java
- alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/ServerStartable.java
- alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/event/GrpcStartableStartedEvent.java
- alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/AlphaIntegrationWithRandomPortTest.java
- alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/tcc/TccConfiguration.java
Generate a random port when alpha.server.port=0
The following configuration can be used to configure a random port range [initialPort...initialPort+portCount] 
`alpha.server.initialPort` default bind port 8080
`alpha.server.portAutoIncrement` enabled automatic Increment, defulat true
`alpha.server.portCount` try to bind the count, default 100
default random port range [8080...8180]
**Note** GrpcStartableStartedEvent  reserve dynamic registration random port to discovery service
> [SCB-1155] Generate a random free gRPC port when alpha.server.port=0

- docs/user_guide.md
- docs/user_guide_zh.md
> [SCB-1195] Modify eureka.enabled to eureka.client.enabled

- alpha/alpha-server/src/main/resources/application.yaml
- omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/pack/omega/connector/grpc/AlphaClusterDiscovery.java
- omega/omega-spring-cloud-consul-starter/pom.xml
- omega/omega-spring-cloud-consul-starter/src/main/java/org/apache/servicecomb/pack/omega/spring/cloud/OmegaSpringConsulAutoConfiguration.java
- omega/omega-spring-cloud-consul-starter/src/main/java/org/apache/servicecomb/pack/omega/spring/cloud/OmegaSpringConsulConfig.java
- omega/omega-spring-cloud-consul-starter/src/main/resources/META-INF/spring.factories
- omega/omega-spring-cloud-eureka-starter/src/main/java/org/apache/servicecomb/pack/omega/spring/cloud/OmegaSpringEurekaConfig.java
- omega/omega-spring-starter/src/main/java/org/apache/servicecomb/pack/omega/spring/OmegaSpringConfig.java
- omega/pom.xml
add dependencies
```xml
<dependency>
<groupId>org.apache.servicecomb.pack</groupId>
<artifactId>omega-spring-cloud-consul-starter</artifactId>
</dependency>
```
add consul paramters
```yaml
alpha:
cluster:
address: localhost:8080
serviceId: servicecomb-alpha-server
register:
type: consul
omega:
instance:
instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port}
spring:
cloud:
consul:
host: 0.0.0.0
port: 8500
discovery:
serviceName: {spring.application.name}
healthCheckPath: /health
healthCheckInterval: 10s
instanceId: ${spring.application.name}-${server.host}-${server.port}
```
You can see the following log
```bash
801  INFO [booking-service,,,] 13797 [main] o.a.s.p.omega.spring.OmegaSpringConfig.alphaClusterConfig : Discovery alpha cluster address 0.0.0.0:8080 …
```
> [SCB-1200] Omega support discovery service consul

- alpha/alpha-server/src/main/resources/schema-mysql.sql
The Mysql table schema in schema-mysql.sql has some problem.
I try to use MySQL as alpha's backend database： 
1.  I package the distribution version use： mvn clean install -DskipTests=true -Prelease
2.  prepare mysql 5.7 db，copy mysql-connector-java-8.0.15.jar in libs2 dictionary
3. run command： java -Dspring.profiles.active=mysql -Dloader.path=./libs2 -D"spring.datasource.url=jdbc:mysql://127.0.0.1:3308/saga?serverTimezone=GMT%2b8&useSSL=false" -jar alpha-server-0.4.0-SNAPSHOT-exec.jar
but encounter one problem， the log： 
```java
17:34:30.224 [main] ERROR org.springframework.boot.web.embedded.tomcat.TomcatStarter - Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException.
Message: Error creating bean with name 'servletEndpointRegistrar' defined in …
```
> fix mysql master_lock table schema wrong default value

- omega/omega-spring-cloud-consul-starter/src/main/java/org/apache/servicecomb/pack/omega/spring/cloud/OmegaSpringConsulConfig.java
- omega/omega-spring-cloud-eureka-starter/src/main/java/org/apache/servicecomb/pack/omega/spring/cloud/OmegaSpringEurekaConfig.java
- omega/omega-spring-starter/src/main/java/org/apache/servicecomb/pack/omega/spring/OmegaSpringConfig.java
When no alpha.cluster.address is configured on the omega side, the default value is 0.0.0.0:8080
> [SCB-1247] Set default value in alpha.cluster.address on omega side

- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/AbstractRecoveryPolicy.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/DefaultRecovery.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/ForwardRecovery.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/OmegaException.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/RecoveryPolicyTimeoutWrapper.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/TransactionTimeoutException.java
- omega/omega-transaction/src/test/java/org/apache/servicecomb/pack/omega/transaction/TransactionAspectTest.java
Use this wrapper to send a request if the @Compensable timeout>0
Terminate thread execution if execution time is greater than the timeout of @Compensable
Exception
* If the interrupt succeeds, a TransactionTimeoutException is thrown and the local transaction is the rollback
* If the interrupt fails, throw an OmegaException
Note: Omega coding advice
* Add short sleep to while true loop. Otherwise, the thread may not be able to terminate.
* Replace the synchronized with ReentrantLock, Otherwise, the thread may not be able to terminate.
> [SCB-1272] Improvement Omega timeout processing, interrupt request thread after the timeout

- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/tcc/DefaultParametersContext.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/tcc/ParametersContext.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/tcc/TccParticipatorAspect.java
---
Change `ParametersContext.putParamters` to `putParameters`
> SCB-1352 Fix typo on ParametersContext class

- scripts/test.sh
Currently script/test.sh contains 3 mvn command execution, it
will continue even if previous mvn command execution failed,
that makes it hard to find out why build fails from pretty long
build logs. So make it fail fast if previous mvn command
execution fails will be helpful.
---
> SCB-1353 Make script/test.sh fail fast.

- omega/omega-transport/omega-transport-hystrix/pom.xml
- omega/omega-transport/omega-transport-hystrix/src/main/java/org/apache/servicecomb/pack/omega/transport/hystrix/HystrixCallableWrapper.java
- omega/omega-transport/omega-transport-hystrix/src/main/java/org/apache/servicecomb/pack/omega/transport/hystrix/HystrixServiceCombAutoConfiguration.java
- omega/omega-transport/omega-transport-hystrix/src/main/java/org/apache/servicecomb/pack/omega/transport/hystrix/OmegaContextCallableWrapper.java
- omega/omega-transport/omega-transport-hystrix/src/main/java/org/apache/servicecomb/pack/omega/transport/hystrix/ServiceCombConcurrencyStrategy.java
- omega/omega-transport/omega-transport-hystrix/src/main/resources/META-INF/spring.factories
- omega/omega-transport/omega-transport-hystrix/src/test/java/org/apache/servicecomb/pack/omega/transport/hystrix/HystrixConcurrencyStrategyTests.java
- omega/omega-transport/omega-transport-hystrix/src/test/java/org/apache/servicecomb/pack/omega/transport/hystrix/HystrixTestApplication.java
- omega/omega-transport/omega-transport-hystrix/src/test/java/org/apache/servicecomb/pack/omega/transport/hystrix/HystrixWithoutConcurrencyStrategyTests.java
- omega/omega-transport/pom.xml
- pom.xml
解决issue #571
我关闭了 #572 ,重新提交了PR
OmegaContext 中使用了 InheritableThreadLocal
在feign调用开启hystrix时,hystrix会为每个feignClient创建线程池.
InheritableThreadLocal在第一次创建线程时,可以正确继承到父线程的线程变量,但是当线程被复用时,InheritableThreadLocal不会被更新,导致无法在feign调用的header里传递globalTxId和localTxId
我参考了spring security解决securityContext 线程变量在使用hystrix时,传递线程变量的方案,针对OmegaContext里的线程变量进行了传递,并提供了可扩展的接口
> SCB-1530 Add omega-transport-hystrix

- alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/spring/integration/akka/AkkaConfigPropertyAdapter.java
```
#redis 单机模式
#akkaConfig:
#redis 哨兵模式
akkaConfig:
akka.persistence.journal.plugin: akka-persistence-redis.journal
akka.persistence.snapshot-store.plugin: akka-persistence-redis.snapshot
akka-persistence-redis:
redis:
mode: sentinel
database: 1
password: ${spring.redis.password}
master: ${spring.redis.sentinel.master}
```
sentinel-list: ${spring.redis.sentinel.nodes}
---
> [SCB-1532] Redis configuration is invalid

- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/TransactionAspect.java
- omega/omega-transaction/src/test/java/org/apache/servicecomb/pack/omega/transaction/TransactionAspectTest.java
> SCB-1011 Added a NPE check in TransactionAspect

- docker-build-config/pom.xml
Changed pom of docker-build-config to support tar long file mode
---
> SCB-1602:added tar file mode

- alpha/alpha-ui/src/main/java/org/apache/servicecomb/pack/alpha/ui/controller/IndexController.java
metric system.load.average.1m does not support windows os[1], Ignore the metric when running in windows
https://github.com/micrometer-metrics/micrometer/blob/6d615c4af01dcc8bf9e9b4d64c5bce7aba23b444/micrometer-core/src/test/java/io/micrometer/core/instrument/binder/system/ProcessorMetricsTest.java#L32
> [SCB-1611] metric system.load.average.1m does not support windows os

- omega/omega-spring-starter/src/main/java/org/apache/servicecomb/pack/omega/spring/OmegaSpringConfig.java
Modify the "OmegaSpringConfig" class of the omega-spring-starter module. When injecting the bean "omegaUniqueIdGenerator", add the @ConditionalOnMissingBean annotation.
> SCB-1282 Support for custom "omegaUniqueIdGenerator" bean.

- alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/SagaActor.java
- alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/model/SagaData.java
- alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/model/TxEntities.java
- alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/spring/integration/akka/SagaDataExtension.java
- alpha/alpha-fsm/src/test/java/org/apache/servicecomb/pack/alpha/fsm/SagaActorTest.java
- alpha/alpha-fsm/src/test/java/org/apache/servicecomb/pack/alpha/fsm/SagaIntegrationTest.java
- alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/fsm/AlphaIntegrationFsmTest.java
Hide the sub-transaction entity details of SagaData by the TxEntities class encapsulation implemented
PR origin: https://github.com/apache/servicecomb-pack/pull/609/files/ed35f7731cbabc762a8dd40dab4651cc7ee26b16#diff-33cf688727150d4153d7fbf08746a450
> [SCB-1658] Improve encapsulation on txEntityMap of SagaData

- alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/SagaActor.java
- alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/model/TxEntities.java
- alpha/alpha-fsm/src/test/java/org/apache/servicecomb/pack/alpha/fsm/model/TxEntitiesTest.java
The order of execution of reverse compensation should be reversed from the start time of the sub-transaction
> SCB-1669 Fixed reverse compensation sort bug in FSM

- alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/AlphaIntegrationTest.java
- alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/AlphaIntegrationWithRandomPortTest.java
Because the table scan mode cannot guarantee the order of asynchronous compensation messages, test case doNotCompensateDuplicateTxOnFailure will occasionally fail on CI
```bash
Failed tests: 
AlphaIntegrationTest.doNotCompensateDuplicateTxOnFailure:289 
Expected: iterable containing [<globalTxId: "b402c45a-ef25-4061-a5d7-a25eff120c3d"
localTxId: "1f438adb-6b62-41f6-bcc6-e11c791b918f"
parentTxId: "70f07983-0aa6-4fc2-99b0-545b43e7c214"
compensationMethod: "method b"
payloads: "service b"
>, <globalTxId: "b402c45a-ef25-4061-a5d7-a25eff120c3d"
localTxId: "a4eafa18-fcdf-4363-b5dd-a9e647096e15"
parentTxId: "bb87ca5b-1fc8-45fe-931e-67eb8e13405f"
compensationMethod: "method a"
payloads: "service a"
>]
but: item 0: was <globalTxId: "b402c45a-ef25-4061-a5d7-a25eff120c3d"
localTxId: …
```
> [SCB-1685] Change Assert method contains to containsInAnyOrder

- omega/omega-transport/omega-transport-resttemplate/pom.xml
- omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/pack/omega/transport/resttemplate/RestTemplateConfig.java
Issue details: https://issues.apache.org/jira/browse/SCB-1690
---
> SCB-1690 omega-transport-resttemplate does not use RestTemplateBuilder

- docs/upgrade_guide/0.6.0-upgrade-guide.md
- docs/upgrade_guide/0.6.0-upgrade-guide_zh.md
- integration-tests/explicit-transaction-context-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/explicitcontext/GreetingService.java
- integration-tests/pack-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/resttemplate/GreetingService.java
- omega/omega-spring-tx/src/test/java/org/apache/servicecomb/pack/omega/transaction/spring/TransactionalUserService.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/RecoveryPolicyFactory.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/TransactionAspect.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/annotations/Compensable.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/annotations/CompensableMode.java
- omega/omega-transaction/src/test/java/org/apache/servicecomb/pack/omega/transaction/DefaultRecoveryTest.java
- omega/omega-transaction/src/test/java/org/apache/servicecomb/pack/omega/transaction/ForwardRecoveryTest.java
- omega/omega-transaction/src/test/java/org/apache/servicecomb/pack/omega/transaction/TransactionAspectTest.java
Add attribute `mode` to the @Compensable annotation, which contains three options:
- forward 
- reverse (default)
- combine (first forward then reverse)
> [SCB-1695] Add attribute mode to @Compensable annotation

- alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/repository/elasticsearch/ElasticsearchTransactionRepository.java
When the ES index does not exist：
[alpha_global_transaction] IndexNotFoundException[no such index]
When the ES index empty：
[alpha_global_transaction/lUADSX5fSI-KrT428q2XOQ] QueryShardException[No mapping found for [beginTime] in order to sort on]
> SCB-1852 Fixed Alpha UI query error when the ES index not exist or empty

- alpha/alpha-core/src/main/java/org/apache/servicecomb/pack/alpha/core/fsm/event/internal/ComponsitedCheckEvent.java
- alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/SagaActor.java
- alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/domain/UpdateTxEventDomain.java
- alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/model/TxEntities.java
- alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/fsm/GrpcOmegaCallback.java
- alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/fsm/AlphaIntegrationFsmTest.java
- alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/fsm/OmegaEventSagaSimulator.java
- omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/CallbackContext.java
* Use message-driven compensation retry instead of recursive compensation
* In Omega, if CallbackContenxt does not contain callbackMethod, send TxCompensateAckFailedEvent to Alpha instead of throwing NPE
> [SCB-2004] Fix compensation retry failure during business service startup

- .github/workflows/ci.yaml
- acceptance-tests/acceptance-test-common/src/test/java/org/apache/servicecomb/pack/StepDefSupport.java
* Add a CI workflow for PRs and push branch master
> [SCB-2199] Add GitHub Actions workflows

- pom.xml
Grpc - from 1.22.0 to 1.35.0
Netty - from 4.1.35 to 4.1.59
Netty-BoringSSL - from 2.0.25 to 2.0.36
Zookeeper - from 3.4.13 to 3.6.2
> [SCB-2192] Updates dependencies to up able to build on ARM64

- omega/omega-transaction/src/test/java/org/apache/servicecomb/pack/omega/transaction/ForwardRecoveryTest.java
ForwardRecoveryTest.throwExceptionWhenRetryReachesMaximum failure in poor performance host
> [SCB-2202] Improve ForwardRecoveryTest.throwExceptionWhenRetryReachesMaximum

- pom.xml
Jacoco 0.7.x does not support Java 11 https://github.com/jacoco/jacoco/issues/551
Gitlab Actions master push build fails
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: …
```
> [SCB-2248] Update jacoco version to 0.8.6 supports Java 11

- pom.xml
CI build fails with JDK 11 https://github.com/apache/servicecomb-pack/actions/runs/714189795
```
Error: Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project pack: Execution default-cli of goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report failed: A required class was missing while executing org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report: javax/xml/bind/DatatypeConverter
```
See also:
https://github.com/trautonen/coveralls-maven-plugin/issues/112
> SCB-2275 Fixed coveralls-maven-plugin fails on Java 11

- alpha/alpha-spec-saga-db/pom.xml
- alpha/alpha-spec-tcc-db/pom.xml
- demo/saga-dubbo-demo/pom.xml
- demo/saga-dubbo-demo/servicea/pom.xml
* JDK8 javadoc tool fails to process the sources (if any of them are annotated with @Transactional).
* Remove duplicate version definitions
> SCB-2486 Fixed version release issues

- demo/saga-dubbo-demo/pom.xml
There are 1 security vulnerabilities found in org.apache.commons:commons-dbcp2 2.1.1
- [MPS-2022-12024](https://www.oscs1024.com/hd/MPS-2022-12024)
Upgrade org.apache.commons:commons-dbcp2 from 2.1.1 to 2.9.0 for vulnerability fix
Ideally, no insecure libs should be used.
Run `mvn compile` succeeded locally.
Run `mvn clean test` succeeded locally. all tests passed.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> SCB-2724 fix(sec): upgrade org.apache.commons:commons-dbcp2 to 2.9.0

- alpha/alpha-server/src/main/resources/application.yaml
> Spring Boot Actuator only exposes the /actuator/health /actuator/info endpoint by default
