pom.xml
=> updated saga.version

docker-build-config/pom.xml, pom.xml, saga-demo/car-rental-service/pom.xml, saga-demo/flight-booking-service/pom.xml, saga-demo/hotel-reservation-service/pom.xml, saga-demo/payment-service/pom.xml, saga-spring/pom.xml
=> JAV-386 minimized config of mixin plugin

saga-core/src/main/java/io/servicecomb/saga/core/BackwardRecovery.java, saga-core/src/main/java/io/servicecomb/saga/core/ForwardRecovery.java, saga-core/src/main/java/io/servicecomb/saga/core/SagaStartFailedException.java, saga-core/src/main/java/io/servicecomb/saga/core/SagaStartTask.java, saga-core/src/main/java/io/servicecomb/saga/core/TransactionTaskConsumer.java, saga-core/src/main/java/io/servicecomb/saga/core/application/SagaExecutionComponent.java, saga-core/src/test/java/io/servicecomb/saga/core/BackwardRecoveryTest.java, saga-core/src/test/java/io/servicecomb/saga/core/ForwardRecoveryTest.java, saga-core/src/test/java/io/servicecomb/saga/core/SagaStartTaskTest.java, saga-core/src/test/java/io/servicecomb/saga/core/application/RetrySagaLogTest.java
reference issue #17 
Signed-off-by: MabinGo <bin.ma@huawei.com>
=> JAV-328 handle scenario on db failure. 

saga-spring/src/main/java/io/servicecomb/saga/spring/SagaController.java, saga-spring/src/main/java/io/servicecomb/saga/spring/SagaEventRepo.java, saga-spring/src/test/java/io/servicecomb/saga/spring/SagaControllerTest.java, saga-spring/src/test/java/io/servicecomb/saga/spring/SagaSpringApplicationTest.java, saga-web/web-site/web/detail.jsp
Signed-off-by: zhengyangyong <yangyong.zheng@huawei.com>
=> JAV-447 add conditional query

saga-web/web-site/web/data2.json, saga-web/web-site/web/result.jsp, saga-web/web-site/web/table.js
通过bootstrap table 动态展示url数据,接口提供方需要解决跨域问题，同时返回的数据缺少total属性
=> 添加了动态获取列表数据

saga-core/src/main/java/io/servicecomb/saga/core/SagaContextImpl.java, saga-core/src/test/java/io/servicecomb/saga/core/SagaIntegrationTest.java
=> JAV-232 used concurrent data structure

saga-demo/dependency-free-transaction-demo/README.md, saga-demo/dependency-free-transaction-demo/demo-tests/src/test/java/io/servicecomb/saga/demo/tests/DemoIT.java, saga-demo/dependency-free-transaction-demo/payment-service/src/main/resources/microservice.yaml
issue #12 
Signed-off-by: Eric Lee <lidagang1@huawei.com>
=> JAV-368 demonstrated usage of crossapp with service center

pom.xml, transports/transport-httpclient-spring/pom.xml, transports/transport-httpclient-spring/src/main/java/io/servicecomb/saga/transports/HttpClientTransportConfig.java, transports/transport-httpclient-spring/src/test/java/io/servicecomb/saga/transports/RestTransportTest.java, transports/transport-httpclient-spring/src/test/resources/log4j2.xml, transports/transport-httpclient/pom.xml, transports/transport-httpclient/src/main/java/io/servicecomb/saga/transports/httpclient/HttpClientTransport.java, transports/transport-httpclient/src/test/java/io/servicecomb/saga/transports/httpclient/HttpClientTransportTest.java
solved issue #20 
Signed-off-by: eric-lee-ltk <lidagang1@huawei.com>
=> added timeout settings for rest transport

saga-spring/src/main/java/io/servicecomb/saga/spring/SagaController.java, saga-spring/src/main/java/io/servicecomb/saga/spring/SagaExecutionQueryService.java, saga-spring/src/test/java/io/servicecomb/saga/spring/SagaSpringApplicationTest.java, saga-web/web-site/web/detail.jsp, saga-web/web-site/web/js/date.js, saga-web/web-site/web/result.jsp
前端时间如果未选择是“NaN-NaN-NaN NaN:NaN:NaN”，需要支持这种格式
=> Jav 438 match front end

saga-web/web-site/web/detail.jsp
=> url params

saga-web/src/main/resources/static/assets/request.js
Signed-off-by: eric-lee-ltk <lidagang1@huawei.com>
=> fixed data type in request

saga-web/src/main/resources/static/assets/request.js, saga-web/src/main/resources/static/request.css, saga-web/src/main/resources/static/request.html
Signed-off-by: eric-lee-ltk <lidagang1@huawei.com>
=> fixed display of loading logo

saga-core/src/main/java/io/servicecomb/saga/core/actors/ActorBasedSagaFactory.java, saga-core/src/main/java/io/servicecomb/saga/core/application/SagaExecutionComponent.java, saga-core/src/main/java/io/servicecomb/saga/core/application/SagaFactory.java, saga-core/src/main/java/io/servicecomb/saga/core/dag/GraphBasedSagaFactory.java, saga-core/src/test/java/io/servicecomb/saga/core/actors/ActorBasedSagaIntegrationTest.java, saga-spring/src/main/java/io/servicecomb/saga/spring/SagaShutdownListener.java, saga-spring/src/main/resources/META-INF/spring.factories
=> gracefully shutdown of actor system

README.md
=> modify invalid links

saga-spring/src/main/java/io/servicecomb/saga/spring/SagaShutdownListener.java
=> add license for SagaShutdownListener

README.md
=> SCB-122 add Apache disclamer and modify website address

alpha/alpha-core/pom.xml, alpha/alpha-core/src/main/java/io/servicecomb/saga/alpha/core/EventType.java, alpha/alpha-core/src/main/java/io/servicecomb/saga/alpha/core/OmegaCallback.java, alpha/alpha-core/src/main/java/io/servicecomb/saga/alpha/core/TxConsistentService.java, alpha/alpha-core/src/main/java/io/servicecomb/saga/alpha/core/TxEventRepository.java, alpha/alpha-core/src/test/java/io/servicecomb/saga/alpha/core/TxConsistentServiceTest.java, alpha/alpha-server/pom.xml, alpha/alpha-server/src/main/java/io/servicecomb/saga/alpha/server/AlphaConfig.java, alpha/alpha-server/src/main/java/io/servicecomb/saga/alpha/server/SwiftTxEventEndpointImpl.java, alpha/alpha-server/src/main/java/io/servicecomb/saga/alpha/server/TxEventEnvelope.java, alpha/alpha-server/src/main/java/io/servicecomb/saga/alpha/server/TxEventEnvelopeRepository.java, alpha/alpha-server/src/test/java/io/servicecomb/saga/alpha/server/AlphaIntegrationTest.java
=> [SCB-99] added compensation logic on tx aborted event

alpha/alpha-core/src/main/java/io/servicecomb/saga/alpha/core/TxConsistentService.java, alpha/alpha-core/src/main/java/io/servicecomb/saga/alpha/core/TxEventRepository.java, alpha/alpha-core/src/test/java/io/servicecomb/saga/alpha/core/TxConsistentServiceTest.java, alpha/alpha-server/src/main/java/io/servicecomb/saga/alpha/server/SpringTxEventRepository.java, alpha/alpha-server/src/main/java/io/servicecomb/saga/alpha/server/TxEventEnvelope.java, alpha/alpha-server/src/main/java/io/servicecomb/saga/alpha/server/TxEventEnvelopeRepository.java, alpha/alpha-server/src/test/java/io/servicecomb/saga/alpha/server/AlphaIntegrationTest.java, omega/omega-context/pom.xml, omega/omega-context/src/main/java/io/servicecomb/saga/omega/context/OmegaContext.java, omega/omega-spring-tx/src/test/java/io/servicecomb/saga/omega/transaction/spring/TransactionInterceptionTest.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/TransactionAspect.java
SCB-141 supported multiple sub tx within the same global tx on a single service
---
=> SCB-140 compensated only distinct events

alpha/alpha-core/src/main/java/io/servicecomb/saga/alpha/core/OmegaCallback.java, alpha/alpha-core/src/main/java/io/servicecomb/saga/alpha/core/TxConsistentService.java, alpha/alpha-core/src/main/java/io/servicecomb/saga/alpha/core/TxEvent.java, alpha/alpha-core/src/test/java/io/servicecomb/saga/alpha/core/TxConsistentServiceTest.java, alpha/alpha-server/src/main/java/io/servicecomb/saga/alpha/server/AlphaConfig.java, alpha/alpha-server/src/main/java/io/servicecomb/saga/alpha/server/SwiftTxEventEndpointImpl.java, alpha/alpha-server/src/main/java/io/servicecomb/saga/alpha/server/TxEventEnvelope.java, alpha/alpha-server/src/main/java/io/servicecomb/saga/alpha/server/TxEventEnvelopeRepository.java, alpha/alpha-server/src/main/resources/schema-mysql.sql, alpha/alpha-server/src/test/java/io/servicecomb/saga/alpha/server/AlphaIntegrationTest.java, omega/omega-connector/omega-connector-thrift/src/main/java/io/servicecomb/saga/omega/connector/thrift/ThriftMessageSender.java, omega/omega-connector/omega-connector-thrift/src/test/java/io/servicecomb/saga/omega/connector/thrift/ThriftMessageSenderTest.java, omega/omega-context/src/main/java/io/servicecomb/saga/omega/context/OmegaContext.java, omega/omega-format/src/test/java/io/servicecomb/saga/omega/format/NativeMessageFormatTest.java, omega/omega-spring-tx/src/main/java/io/servicecomb/saga/omega/transaction/spring/CompensableAnnotationProcessor.java, omega/omega-spring-tx/src/main/java/io/servicecomb/saga/omega/transaction/spring/CompensableMethodCheckingCallback.java, omega/omega-spring-tx/src/main/java/io/servicecomb/saga/omega/transaction/spring/TransactionAspectConfig.java, omega/omega-spring-tx/src/test/java/io/servicecomb/saga/omega/transaction/spring/TransactionInterceptionTest.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/FailedTransactionInterceptor.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/MessageHandler.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/PostTransactionInterceptor.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/PreTransactionInterceptor.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/TransactionAspect.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/TxAbortedEvent.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/TxEndedEvent.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/TxEvent.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/TxStartedEvent.java, omega/omega-transaction/src/test/java/io/servicecomb/saga/omega/transaction/PostTransactionInterceptorTest.java, omega/omega-transaction/src/test/java/io/servicecomb/saga/omega/transaction/PreTransactionInterceptorTest.java, pack-contracts/pack-contract-thrift/src/main/java/io/servicecomb/saga/pack/contracts/thrift/SwiftTxEvent.java
=> [SCB-98] remote compensation context

transports/transport-resttemplate/src/main/java/io/servicecomb/saga/transports/resttemplate/RestTemplateTransport.java
=> SCB-104 Removed the get method in the RestTemplateTransport

omega/omega-context/src/main/java/io/servicecomb/saga/omega/context/OmegaContext.java, omega/omega-spring-tx/src/main/java/io/servicecomb/saga/omega/transaction/spring/TransactionAspectConfig.java, omega/omega-spring-tx/src/test/java/io/servicecomb/saga/omega/transaction/spring/TransactionInterceptionTest.java, omega/omega-spring-tx/src/test/java/io/servicecomb/saga/omega/transaction/spring/User.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/CompensationMessageHandler.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/FailedTransactionInterceptor.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/MessageHandler.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/TxCompensatedEvent.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/TxEndedEvent.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/TxEvent.java, omega/omega-transaction/src/main/java/io/servicecomb/saga/omega/transaction/TxStartedEvent.java, omega/omega-transaction/src/test/java/io/servicecomb/saga/omega/transaction/CompensationMessageHandlerTest.java, omega/omega-transaction/src/test/java/io/servicecomb/saga/omega/transaction/PostTransactionInterceptorTest.java
=> [SCB-152] send compensated event

alpha/alpha-server/pom.xml, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/AlphaConfig.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/GrpcOmegaCallback.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/GrpcOmegaStreamObserver.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/GrpcStartable.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/GrpcTxEventEndpointImpl.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/GrpcTxEventStreamObserver.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/saga/alpha/server/AlphaIntegrationTest.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/saga/alpha/server/GrpcTxEventStreamObserverTest.java, omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/GrpcClientMessageSender.java, omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/GrpcCompensateStreamObserver.java, omega/omega-spring-starter/src/main/java/org/apache/servicecomb/saga/omega/spring/OmegaSpringConfig.java, omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/saga/omega/transport/resttemplate/TransactionHandlerInterceptor.java, pack-contracts/pack-contract-grpc/src/main/proto/GrpcTxEvent.proto
=> SCB-138 use grpc bidirectional streaming to connect alpha and omega

omega/omega-context/src/main/java/org/apache/servicecomb/saga/omega/context/OmegaContext.java, omega/omega-spring-tx/pom.xml, omega/omega-spring-tx/src/main/java/org/apache/servicecomb/saga/omega/transaction/spring/CompensableAnnotationProcessor.java, omega/omega-spring-tx/src/main/java/org/apache/servicecomb/saga/omega/transaction/spring/ExecutorFieldCallback.java, omega/omega-spring-tx/src/main/java/org/apache/servicecomb/saga/omega/transaction/spring/annotations/OmegaContextAware.java, omega/omega-spring-tx/src/test/java/org/apache/servicecomb/saga/omega/transaction/spring/CompensableAnnotationCheckingTest.java, omega/omega-spring-tx/src/test/java/org/apache/servicecomb/saga/omega/transaction/spring/MisconfiguredAnnotation.java, omega/omega-spring-tx/src/test/java/org/apache/servicecomb/saga/omega/transaction/spring/TransactionInterceptionTest.java, omega/omega-spring-tx/src/test/java/org/apache/servicecomb/saga/omega/transaction/spring/UserRepository.java
=> [SCB-100] async support

pom.xml
=> SCB-157 Updated the pom setting for apache release

integration-tests/pack-tests/src/test/java/org/apache/servicecomb/saga/integration/pack/tests/GreetingController.java, integration-tests/pack-tests/src/test/java/org/apache/servicecomb/saga/integration/pack/tests/PackIT.java, integration-tests/pack-tests/src/test/java/org/apache/servicecomb/saga/integration/pack/tests/TxEventEnvelope.java, omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/GrpcClientMessageSender.java, omega/omega-context/src/main/java/org/apache/servicecomb/saga/omega/context/annotations/SagaStart.java, omega/omega-spring-tx/src/main/java/org/apache/servicecomb/saga/omega/transaction/spring/CompensableMethodCheckingCallback.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/SagaEndedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAnnotationProcessor.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/SagaStartedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/TransactionAspect.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAnnotationProcessorTest.java, omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/saga/omega/transport/resttemplate/TransactionClientHttpRequestInterceptor.java, omega/omega-transport/omega-transport-resttemplate/src/test/java/org/apache/servicecomb/saga/omega/transport/resttemplate/TransactionClientHttpRequestInterceptorTest.java
=> [WIP]SCB-173 mark start of saga

integration-tests/pack-tests/src/test/java/org/apache/servicecomb/saga/integration/pack/tests/PackIT.java, omega/omega-connector/omega-connector-grpc/pom.xml, omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/GrpcClientMessageSender.java, omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSender.java, omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSenderTest.java, omega/omega-connector/omega-connector-grpc/src/test/resources/log4j2-test.xml, omega/omega-format/src/main/java/org/apache/servicecomb/saga/omega/format/MessageFormat.java, omega/omega-format/src/test/java/org/apache/servicecomb/saga/omega/format/KryoMessageFormatTest.java, omega/omega-format/src/test/java/org/apache/servicecomb/saga/omega/format/MessageFormatTestBase.java, omega/omega-spring-starter/src/main/java/org/apache/servicecomb/saga/omega/spring/OmegaSpringConfig.java, omega/omega-spring-tx/pom.xml, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/MessageSender.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/MessageSerializer.java
=> [SCB-168] load balance

omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/GrpcClientMessageSender.java, omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSenderTest.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/SagaEndedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/SagaStartedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/TxAbortedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/TxCompensatedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/TxEndedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/TxEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/TxStartedEvent.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/CompensableInterceptorTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/CompensationMessageHandlerTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAnnotationProcessorTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAspectTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/TransactionAspectTest.java
---
https://issues.apache.org/jira/browse/SCB-228
=> SCB-228 Update to replace the type of TxEvent with Enum

omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSender.java, omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/PushBackReconnectRunnable.java, omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSenderTest.java, omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/PushBackReconnectRunnableTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAspectTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/TransactionAspectTest.java
=> SCB-211 wait until connection recover instead of try sending

.travis.yml
=> SCB-233 update to deploy only with non PR building

alpha/alpha-core/src/main/java/org/apache/servicecomb/saga/alpha/core/TxConsistentService.java, alpha/alpha-core/src/test/java/org/apache/servicecomb/saga/alpha/core/CompositeOmegaCallbackTest.java, alpha/alpha-core/src/test/java/org/apache/servicecomb/saga/alpha/core/TxConsistentServiceTest.java, alpha/alpha-core/src/test/java/org/apache/servicecomb/saga/alpha/core/TxEventMaker.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/saga/alpha/server/AlphaIntegrationTest.java, omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSenderTest.java, omega/omega-transaction/pom.xml, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/SagaEndedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/SagaStartedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/TxAbortedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/TxCompensatedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/TxEndedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/TxEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/TxStartedEvent.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/CompensableInterceptorTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/CompensationMessageHandlerTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAnnotationProcessorTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAspectTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/TransactionAspectTest.java, pack-common/pom.xml, pack-common/src/main/java/org/apache/servicecomb/saga/common/EventType.java, pom.xml
---
https://issues.apache.org/jira/browse/SCB-232
=> SCB-232 EventType should be same between omega and alpha

alpha/alpha-core/src/main/java/org/apache/servicecomb/saga/alpha/core/TxConsistentService.java, alpha/alpha-core/src/main/java/org/apache/servicecomb/saga/alpha/core/TxEvent.java, alpha/alpha-core/src/main/java/org/apache/servicecomb/saga/alpha/core/TxEventRepository.java, alpha/alpha-core/src/test/java/org/apache/servicecomb/saga/alpha/core/TxConsistentServiceTest.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/SpringTxEventRepository.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/TxEventEnvelopeRepository.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/saga/alpha/server/AlphaIntegrationTest.java, integration-tests/pack-tests/src/test/java/org/apache/servicecomb/saga/integration/pack/tests/PackIT.java
=> SCB-220 avoid redundant compensation

omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSender.java, omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/RetryableMessageSender.java, omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSenderTest.java, omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/RetryableMessageSenderTest.java, omega/omega-spring-starter/src/main/java/org/apache/servicecomb/saga/omega/spring/OmegaSpringConfig.java, omega/omega-transaction/pom.xml, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAnnotationProcessor.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAnnotationProcessorTest.java, pom.xml
=> SCB-234 fail fast at SagaStart if all alpha clusters are down

alpha/alpha-server/pom.xml, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/AlphaConfig.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/CommandEntityRepository.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/SpringCommandRepository.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/saga/alpha/server/AlphaIntegrationTest.java, integration-tests/pack-tests/pom.xml, omega/pom.xml, pom.xml, saga-core/pom.xml, saga-core/src/test/java/org/apache/servicecomb/saga/core/CompositeSagaResponseTest.java, saga-demo/conditional-transaction-demo/conditional-transaction-demo-tests/pom.xml, saga-demo/conditional-transaction-demo/inventory/pom.xml, saga-demo/conditional-transaction-demo/payment/pom.xml, saga-demo/dependency-free-transaction-demo/demo-tests/pom.xml, saga-demo/dependency-free-transaction-demo/hotel-reservation-service/pom.xml, saga-demo/dependency-free-transaction-demo/payment-service/pom.xml, saga-demo/dependency-free-transaction-demo/pom.xml, saga-demo/pom.xml, saga-discovery/saga-discovery-servicecenter/pom.xml, saga-spring/pom.xml, saga-web/pom.xml
=> SCB-270 in order compensation

saga-demo/pack-demo/README.md, saga-demo/pack-demo/booking/pom.xml, saga-demo/pack-demo/booking/src/main/java/org/apache/servicecomb/saga/demo/pack/booking/Application.java, saga-demo/pack-demo/booking/src/main/java/org/apache/servicecomb/saga/demo/pack/booking/BookingController.java, saga-demo/pack-demo/booking/src/main/resources/application.yaml, saga-demo/pack-demo/car/pom.xml, saga-demo/pack-demo/car/src/main/java/org/apache/servicecomb/saga/demo/pack/car/Application.java, saga-demo/pack-demo/car/src/main/java/org/apache/servicecomb/saga/demo/pack/car/CarBooking.java, saga-demo/pack-demo/car/src/main/java/org/apache/servicecomb/saga/demo/pack/car/CarBookingController.java, saga-demo/pack-demo/car/src/main/java/org/apache/servicecomb/saga/demo/pack/car/CarBookingService.java, saga-demo/pack-demo/car/src/main/resources/application.yaml, saga-demo/pack-demo/docker-compose.yaml, saga-demo/pack-demo/hotel/pom.xml, saga-demo/pack-demo/hotel/src/main/java/org/apache/servicecomb/saga/demo/pack/hotel/Application.java, saga-demo/pack-demo/hotel/src/main/java/org/apache/servicecomb/saga/demo/pack/hotel/HotelBooking.java, saga-demo/pack-demo/hotel/src/main/java/org/apache/servicecomb/saga/demo/pack/hotel/HotelBookingController.java, saga-demo/pack-demo/hotel/src/main/java/org/apache/servicecomb/saga/demo/pack/hotel/HotelBookingService.java, saga-demo/pack-demo/hotel/src/main/resources/application.yaml, saga-demo/pack-demo/pom.xml, saga-demo/pom.xml
=> SCB-151 Update to add the pack-demo

acceptance-tests/acceptance-pack/src/test/java/org/apache/servicecomb/saga/PackStepdefs.java, acceptance-tests/acceptance-pack/src/test/resources/pack_compensation_scenario.feature, acceptance-tests/pom.xml, alpha/alpha-server/src/test/java/org/apache/servicecomb/saga/alpha/server/AlphaIntegrationTest.java
=> SCB-278 added successful compensation scenario

omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/EventAwareInterceptor.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/TimeAwareInterceptor.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAspectTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/TimeAwareInterceptorTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/TransactionAspectTest.java
---
https://issues.apache.org/jira/browse/SCB-305
=> SCB-305 postInterceptor should throw the exception when the timeout happens

saga-demo/dependency-free-transaction-demo/docker-compose.yaml
change saga-spring port to made same as readme.md
=> Change saga-spring port to made same as readme.md #131

omega/omega-context/src/test/java/org/apache/servicecomb/saga/omega/context/UniqueIdGeneratorTest.java, omega/omega-transport/omega-transport-servicecomb/pom.xml, omega/omega-transport/omega-transport-servicecomb/src/main/java/org/apache/servicecomb/saga/omega/transport/servicecomb/SagaConsumerHandler.java, omega/omega-transport/omega-transport-servicecomb/src/main/java/org/apache/servicecomb/saga/omega/transport/servicecomb/SagaProviderHandler.java, omega/omega-transport/omega-transport-servicecomb/src/main/resources/config/cse.handler.xml, omega/omega-transport/omega-transport-servicecomb/src/test/java/org/apache/servicecomb/saga/omega/transport/servicecomb/SagaConsumerHandlerTest.java, omega/omega-transport/omega-transport-servicecomb/src/test/java/org/apache/servicecomb/saga/omega/transport/servicecomb/SagaProviderHandlerTest.java, omega/omega-transport/pom.xml, pom.xml
=> SCB-243 able to intercept old java chassis requests

README.md, README_ZH.md, alpha/alpha-server/src/test/java/org/apache/servicecomb/saga/alpha/server/AlphaIntegrationTest.java, docs/design.md, docs/design_zh.md, docs/user_guide.md, docs/user_guide_zh.md, omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSenderTest.java, saga-demo/pack-demo/booking/pom.xml
=> SCB-330 add user guide and Chinese version of docs

alpha/alpha-server/pom.xml, pom.xml, saga-distribution/pom.xml, saga-distribution/src/assembly/assembly.xml
For generating alpha-server single jar:
```
cd alpha/alpha-server
mvn clean install spring-boot:repackage
```
For generating the client dependency and demo package:
```
cd saga-distribution
mvn clean package -Prelease
```
---
=> SCB-346 Prepare 1.0-m1 release

pom.xml, saga-persistence/pom.xml, saga-persistence/saga-persistence-jpa/pom.xml, saga-persistence/saga-persistence-jpa/src/main/java/org/apache/servicecomb/saga/persistence/jpa/EclipseLinkJpaConfiguration.java, saga-persistence/saga-persistence-jpa/src/main/resources/META-INF/spring.factories
The saga-persistence module is needed for connecting to databases.
---
=> [SCB-346] Add saga-persistence back

alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/SpringTxTimeoutRepository.java, docs/faq/cn/how_to_use_mysql_as_alpha_backend_database.md, docs/faq/en/how_to_use_mysql_as_alpha_backend_database.md, docs/user_guide.md, docs/user_guide_zh.md
=> SCB-330 add guides to run executable alpha server

saga-demo/booking/README.md
Signed-off-by: lijasonvip <libo75@huawei.com>
---
=> SCB-378 update saga demo readme to fix docker-compose.yml file path

docs/faq/cn/how_to_use_mysql_as_alpha_backend_database.md, docs/faq/en/how_to_use_mysql_as_alpha_backend_database.md, saga-demo/booking/README.md, saga-demo/booking/docker-compose.yaml
=> SCB-330 fix guide of mysql

docs/user_guide.md
=> SCB-395 remove redudant lines

saga-distribution/src/release/NOTICE, saga-distribution/src/release/licenses/NOTICE-grpc, saga-distribution/src/release/licenses/NOTICE-netty, saga-distribution/src/release/licenses/NOTICE-tomcat
=> [SCB-260] Add third party notices

docs/faq/cn/how_to_use_mysql_as_alpha_backend_database.md, docs/faq/en/how_to_use_mysql_as_alpha_backend_database.md, docs/user_guide.md, docs/user_guide_zh.md, saga-demo/booking/README.md, saga-demo/booking/booking/src/main/java/org/apache/servicecomb/saga/demo/pack/booking/BookingController.java
=> SCB-400 add guides to run demo without docker compose

saga-distribution/src/assembly/bin.xml, saga-distribution/src/assembly/src.xml
=> [SCB-404] Use different base folder for source and binary package

acceptance-tests/acceptance-pack/pom.xml, acceptance-tests/acceptance-pack/src/test/java/org/apache/servicecomb/saga/PackStepdefs.java, pom.xml, saga-demo/booking/booking/pom.xml, saga-demo/booking/car/pom.xml, saga-demo/booking/hotel/pom.xml, saga-demo/pom.xml
=> SCB-390 Update to introduece the byteman to the acceptance tests

omega/omega-context/src/main/java/org/apache/servicecomb/saga/omega/context/CompensationContext.java
change type of CompensationContext.contexts to ConcurrentHashMap
=> [SCB-426] change type of CompensationContext.contexts to ConcurrentHashMap

omega/omega-spring-starter/src/main/java/org/apache/servicecomb/saga/omega/spring/OmegaSpringConfig.java
在spring boot 项目中存在不同业务的IdGenerator Bean
避免在引入omega 时，导致IdGenerator 冲突
---
=> SCB-428 Changed idGenerator bean name omegaUniquaIdGenerator

pom.xml, saga-persistence/saga-persistence-jpa/src/main/java/org/apache/servicecomb/saga/persistence/jpa/EclipseLinkJpaConfiguration.java
The Saga persistent need to updated which the API change since 1.5.x.
=> SCB-429 Upgraded the Spring Boot version to 1.5.10

FAQ.md, FAQ_ZH.md, README.md, README_ZH.md
=> [SCB-437] Add a FAQ list

saga-demo/booking/README.md, saga-demo/booking/docker-compose.yaml, saga-demo/booking/saga-demo.sh
=> SCB-436 Clean up the docker-compose file of booking demo

acceptance-tests/acceptance-pack/pom.xml, acceptance-tests/acceptance-pack/src/test/java/org/apache/servicecomb/saga/PackStepdefs.java, alpha/alpha-server/pom.xml, integration-tests/pack-tests/pom.xml, integration-tests/pack-tests/src/test/resources/log4j2.xml, pom.xml, saga-demo/booking/booking/src/main/resources/log4j2.xml, saga-demo/booking/car/src/main/resources/log4j2.xml, saga-demo/booking/hotel/src/main/resources/log4j2.xml, saga-demo/pom.xml, saga-persistence/saga-persistence-jpa/pom.xml
Support to build the Alpha Server with Spring Boot 2.0 by using -Pspring-boot-2
TODO: Upgrade the demos to Spring Boot 2.0
=> SCB-410 Alpha Service upgraded to Spring Boot 2.0

omega/omega-transport/omega-transport-servicecomb/pom.xml, omega/omega-transport/omega-transport-servicecomb/src/main/java/org/apache/servicecomb/saga/omega/transport/servicecomb/SagaConsumerHandler.java, omega/omega-transport/omega-transport-servicecomb/src/main/java/org/apache/servicecomb/saga/omega/transport/servicecomb/SagaProviderHandler.java, omega/omega-transport/omega-transport-servicecomb/src/test/java/org/apache/servicecomb/saga/omega/transport/servicecomb/SagaConsumerHandlerTest.java, omega/omega-transport/omega-transport-servicecomb/src/test/java/org/apache/servicecomb/saga/omega/transport/servicecomb/SagaProviderHandlerTest.java, pom.xml
=> [SCB-464] Upgrade to Java Chassis 1.0.0-m1

omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/GrpcClientMessageSender.java
=> SCB-480 Update to add the timeout in the GrpcTxEvent

acceptance-tests/acceptance-pack/src/test/java/org/apache/servicecomb/saga/PackStepdefs.java, acceptance-tests/acceptance-pack/src/test/resources/pack_compensation_scenario.feature, acceptance-tests/acceptance-pack/src/test/resources/pack_success_scenario.feature, acceptance-tests/acceptance-pack/src/test/resources/pack_timeout_scenario.feature, alpha/alpha-core/src/main/java/org/apache/servicecomb/saga/alpha/core/TxConsistentService.java, alpha/alpha-core/src/main/java/org/apache/servicecomb/saga/alpha/core/TxEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAnnotationProcessor.java, pom.xml
=> SCB-505 Update to throw exception when the transaction timeout

alpha/alpha-server/src/main/resources/schema-mysql.sql, alpha/alpha-server/src/main/resources/schema-postgresql.sql
(#182 )update the length of field serviceName from varchar(16) to varchar(36)
---
=> SCB-545 (#182 )update the length of field serviceName from varchar(16) to varchar(36)

omega/omega-transport/omega-transport-dubbo/src/main/java/org/apache/servicecomb/saga/omega/transport/dubbo/SagaDubboConsumerFilter.java, omega/omega-transport/omega-transport-dubbo/src/main/java/org/apache/servicecomb/saga/omega/transport/dubbo/SagaDubboProviderFilter.java, omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/saga/omega/transport/resttemplate/RestTemplateConfig.java, omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/saga/omega/transport/resttemplate/TransactionClientHttpRequestInterceptor.java, omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/saga/omega/transport/resttemplate/TransactionHandlerInterceptor.java, omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/saga/omega/transport/resttemplate/WebConfig.java, omega/omega-transport/omega-transport-servicecomb/src/main/java/org/apache/servicecomb/saga/omega/transport/servicecomb/SagaConsumerHandler.java, omega/omega-transport/omega-transport-servicecomb/src/main/java/org/apache/servicecomb/saga/omega/transport/servicecomb/SagaProviderHandler.java
Now the demo application can use enableOmega or not.
=> SCB-571 Decouple OmegaContext in the Application

omega/omega-transport/omega-transport-dubbo/src/test/java/SagaDubboConsumerFilterTest.java, pom.xml
=> SCB-583 update the spring boot version

README.md, README_ZH.md
=> [SCB-475] Add section for downloading latest release in README

omega/omega-transport/omega-transport-dubbo/src/main/java/org/apache/servicecomb/saga/omega/transport/dubbo/SagaDubboConsumerFilter.java, omega/omega-transport/omega-transport-dubbo/src/main/java/org/apache/servicecomb/saga/omega/transport/dubbo/SagaDubboProviderFilter.java, omega/omega-transport/omega-transport-dubbo/src/test/java/SagaDubboConsumerFilterTest.java, omega/omega-transport/omega-transport-dubbo/src/test/java/SagaDubboProviderFilterTest.java
Fixed the Dubbo*Filter test errors  by injecting the OmegaContext separately.
=> SCB-584 Fixed the Dubbo*Filter test errors 

pom.xml
Signed-off-by: Eric Lee <eric.lee.ltk@gmail.com>
---
=> SCB-639 upgrade docker maven plugin to 0.26.0

saga-demo/saga-spring-cloud-demo/README.md
=> Fix typos in README.md

saga-demo/saga-dubbo-demo/saga-dubbo-demo.sh, saga-demo/saga-spring-cloud-demo/saga-demo.sh
=> [SCB-647] Add missing ASF header for shell scripts

saga-demo/saga-dubbo-demo/docker-compose-alpha.yaml, saga-demo/saga-dubbo-demo/docker-compose-demo.yaml, saga-demo/saga-dubbo-demo/saga-dubbo-demo.sh
Signed-off-by: Eric Lee <eric.lee.ltk@gmail.com>
---
=> SCB-660 seperate alpha with other services in docker compose

saga-distribution/pom.xml, saga-distribution/src/release/LICENSE, saga-distribution/src/release/licenses/LICENSE-openfeign
1. Add the omega-transport-feign into distribution kit
2. Add the Openfeign LICENSE to the release/licenses fold.
=> SCB-732 Add the omega-transport-feign into distribution kit and updated LICENSE 

omega/omega-transport/omega-transport-servicecomb/pom.xml, pom.xml
=> [SCB-750] Add missing dependency management

pom.xml, saga-distribution/src/release/LICENSE
=> SCB-766 Upgraded spring boot version 1.5.13 and 2.0.3.

alpha/alpha-server/pom.xml, saga-persistence/saga-persistence-jpa/src/main/java/org/apache/servicecomb/saga/persistence/jpa/EclipseLinkJpaConfiguration.java
There are some log output setting is not right in Alpha-server, such as the JPA related log is still sent to stand output. 
使alpha-server的log4j2配置生效，同时jpa的日志也使用日志框架打印出来
1. 使alpha-server的log4j2配置生效
2. jpa的日志也使用日志框架打印出来
- [ x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ x ] Each commit in the pull request should have a meaningful subject line and body.
- [ x ] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` …
=> [SCB-806] Polish alpha-server logger setting

pom.xml
The project failed to build with -Prelease.
---
=> [SCB-821] Add missing dependency management for omega-transport-feign

saga-distribution/src/release/LICENSE, saga-distribution/src/release/NOTICE
=> [SCB-822] Update LICENSE/NOTICE

saga-demo/conditional-transaction-demo/inventory/pom.xml, saga-demo/conditional-transaction-demo/membership/pom.xml, saga-demo/conditional-transaction-demo/payment/pom.xml, saga-demo/conditional-transaction-demo/supplier/pom.xml, saga-demo/dependency-free-transaction-demo/car-rental-service/pom.xml, saga-demo/dependency-free-transaction-demo/flight-booking-service/pom.xml, saga-demo/dependency-free-transaction-demo/hotel-reservation-service/pom.xml, saga-demo/dependency-free-transaction-demo/payment-service/pom.xml
- **The demos cannot be built since the essential docker images are not built without docker plugin activation being specified**
- **Not a large PR**
---
=> [SCB-824] Fix the bug that demos cannot be built: add docker plugin activation tag for demos

omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/SagaStartAnnotationProcessor.java
=> [SCB-825] fix SagaStartAnnotationProcessor class  bug

alpha/alpha-server/src/main/resources/schema-mysql.sql, alpha/alpha-server/src/main/resources/schema-postgresql.sql
https://issues.apache.org/jira/browse/SCB-829
=> SCB-829 An index on TxEvent (globalTxId) should be added

pom.xml
Signed-off-by: zhengyangyong <yangyong.zheng@huawei.com>
---
=> [SCB-830] update chassis from 1.0.0-m2 to 1.0.0

pom.xml
=> SCB-834 Upgrade Akka version to 2.5.14

omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/saga/omega/connector/grpc/LoadBalancedClusterMessageSenderTest.java
Signed-off-by: zhengyangyong <yangyong.zheng@huawei.com>
---
=> SCB-831 fix test case failed on windows environment in LoadBalancedClusterMessageSenderTest

saga-demo/saga-k8s-resources/README.md, saga-demo/saga-k8s-resources/base/alpha.yaml, saga-demo/saga-k8s-resources/base/jmeter-collector.yaml, saga-demo/saga-k8s-resources/spring-demo/booking.yaml, saga-demo/saga-k8s-resources/spring-demo/car.yaml, saga-demo/saga-k8s-resources/spring-demo/hotel.yaml, saga-demo/saga-k8s-resources/spring-demo/test/jmeter.yaml
- **In this PR, all the k8s resources refer to public images from Huawei cloud. A jmeter-collector services is added which will interact with the test jmeter to collect and display test results**
- **Not a large PR**
---
=> [SCB-823] Refer to public images, add testing facilities

saga-demo/saga-k8s-resources/base/alpha.yaml, saga-demo/saga-k8s-resources/base/jmeter-collector.yaml, saga-demo/saga-k8s-resources/spring-demo/booking.yaml, saga-demo/saga-k8s-resources/spring-demo/car.yaml, saga-demo/saga-k8s-resources/spring-demo/hotel.yaml, saga-demo/saga-k8s-resources/spring-demo/test/jmeter.yaml
- **Fix the repo name of public dockerhub images**
- **Not a large PR**
---
=> [SCB-823]Fix the spring-demo image repo name.

saga-format/pom.xml, saga-format/src/main/java/org/apache/servicecomb/saga/format/ChildrenExtractor.java, saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonRestOperation.java, saga-format/src/main/java/org/apache/servicecomb/saga/format/JacksonSagaEventFormat.java, saga-format/src/main/java/org/apache/servicecomb/saga/format/JsonSagaDefinition.java, saga-format/src/test/java/org/apache/servicecomb/saga/format/JacksonFromJsonFormatTest.java, saga-format/src/test/java/org/apache/servicecomb/saga/format/JacksonRestOperationTest.java, saga-format/src/test/java/org/apache/servicecomb/saga/format/JsonRestSagaRequestTest.java, saga-format/src/test/java/org/apache/servicecomb/saga/format/SagaEventFormatTest.java
Rewrite the lamda function in saga-format to support JDK 7
=> [SCB-855]Support JDK7 in saga-format

docs/load_test.md, saga-demo/saga-k8s-resources/README.md, saga-demo/saga-k8s-resources/base/alpha.yaml
- Add the guide of load testing with kubernetes
- Expose port 8090 in alpha-server in kubernetes cluster
=> Add the document of load testing.

alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/tcc/GrpcTccEventService.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/saga/alpha/tcc/server/AlphaTccServerTest.java
Add onTccCoordinated grpc method for alpha server.
=> SCB-856 Add onTccCoordinated grpc method for alpha server.

omega/omega-context/src/main/java/org/apache/servicecomb/saga/omega/context/CallbackContext.java, omega/omega-context/src/main/java/org/apache/servicecomb/saga/omega/context/OmegaContext.java, omega/omega-spring-starter/src/main/java/org/apache/servicecomb/saga/omega/spring/OmegaSpringConfig.java, omega/omega-spring-tx/src/main/java/org/apache/servicecomb/saga/omega/transaction/spring/CompensableMethodCheckingCallback.java, omega/omega-spring-tx/src/main/java/org/apache/servicecomb/saga/omega/transaction/spring/ExecutorFieldCallback.java, omega/omega-spring-tx/src/main/java/org/apache/servicecomb/saga/omega/transaction/spring/MethodCheckingCallback.java, omega/omega-spring-tx/src/main/java/org/apache/servicecomb/saga/omega/transaction/spring/ParticipateAnnotationProcessor.java, omega/omega-spring-tx/src/main/java/org/apache/servicecomb/saga/omega/transaction/spring/ParticipateMethodCheckingCallback.java, omega/omega-spring-tx/src/main/java/org/apache/servicecomb/saga/omega/transaction/spring/TransactionAspectConfig.java, omega/omega-spring-tx/src/test/java/org/apache/servicecomb/saga/omega/transaction/spring/MessageConfig.java, omega/omega-spring-tx/src/test/java/org/apache/servicecomb/saga/omega/transaction/spring/TccInterceptorTest.java, omega/omega-spring-tx/src/test/java/org/apache/servicecomb/saga/omega/transaction/spring/TccUserService.java, omega/omega-spring-tx/src/test/java/org/apache/servicecomb/saga/omega/transaction/spring/TccUserServiceMain.java, omega/omega-spring-tx/src/test/java/org/apache/servicecomb/saga/omega/transaction/spring/TransactionInterceptionTest.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/CompensationMessageHandler.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/tcc/CoordinateMessageHandler.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/tcc/TccParticipatorAspect.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/tcc/events/CoordinatedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/tcc/events/ParticipatedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/tcc/events/TccEndedEvent.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/saga/omega/transaction/tcc/events/TccStartedEvent.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/CompensationMessageHandlerTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/tcc/CoordinateMessageHandlerTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/saga/omega/transaction/tcc/TccParticipatorAspectTest.java
Implement of Omega TCC coordinate command callback and refactor
=> SCB-876 Implement of Omega TCC coordinate command callback and refactor

alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/tcc/callback/OmegaCallbackWrapper.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/tcc/registry/OmegaCallbacksRegistry.java
=> * SCB-856 Fixed the way to remove specific OmegaCallback.

alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/SpringTxEventRepository.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/TxEventEnvelopeRepository.java
https://issues.apache.org/jira/browse/SCB-885
=> SCB-885 saga alpha event scanner delete duplicate events sql optimization

acceptance-tests/acceptance-pack-tcc-spring-demo/pom.xml, acceptance-tests/acceptance-pack-tcc-spring-demo/src/test/java/org/apache/servicecomb/saga/PackStepdefs.java, acceptance-tests/acceptance-pack-tcc-spring-demo/src/test/java/org/apache/servicecomb/saga/RunCucumberIT.java, acceptance-tests/acceptance-pack-tcc-spring-demo/src/test/resources/log4j2-test.xml, acceptance-tests/acceptance-pack-tcc-spring-demo/src/test/resources/pack_tcc_cancel_scenario.feature, acceptance-tests/acceptance-pack-tcc-spring-demo/src/test/resources/pack_tcc_confirm_scenario.feature, acceptance-tests/pom.xml, alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/tcc/registry/TransactionEventRegistry.java, omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/saga/omega/connector/grpc/GrpcCoordinateStreamObserver.java, saga-demo/tcc-spring-demo/README.md, saga-demo/tcc-spring-demo/inventory/src/main/java/org/apache/servicecomb/saga/demo/pack/inventory/InventoryService.java, saga-demo/tcc-spring-demo/inventory/src/main/java/org/apache/servicecomb/saga/demo/pack/inventory/ProductController.java, saga-demo/tcc-spring-demo/inventory/src/main/java/org/apache/servicecomb/saga/demo/pack/inventory/ProductOrder.java, saga-demo/tcc-spring-demo/inventory/src/test/java/org/apache/servicecomb/saga/demo/pack/inventory/InventoryServiceTest.java, saga-demo/tcc-spring-demo/inventory/src/test/java/org/apache/servicecomb/saga/demo/pack/inventory/ProductControllerTest.java, saga-demo/tcc-spring-demo/ordering/src/main/java/org/apache/servicecomb/saga/demo/pack/ordering/OrderingController.java, saga-demo/tcc-spring-demo/payment/src/main/java/org/apache/servicecomb/saga/demo/pack/payment/PaymentController.java, saga-demo/tcc-spring-demo/payment/src/test/java/org/apache/servicecomb/saga/demo/pack/payment/PaymentControllerTest.java
The accept test has two scenarios:
1. All the sub transaction succeeded, omega calls the confirm method.
2. Something wrong with the sub transaction, omega only calls the succeed services's cancel method.
I also fixed some minor error of tcc-spring demo and alpha server.
=> SCB-819 Added accept test for tcc-spring-demo. 

alpha/alpha-server/src/main/resources/schema-postgresql.sql
Revise TCC DDL for postgresql.
=> SCB-856 Revise TCC DDL for postgresql.

omega/omega-spring-tx/src/main/java/org/apache/servicecomb/saga/omega/transaction/spring/TransactionAspectConfig.java
Clean up @order annotation in TransactionAspectConfig.
=> SCB-916 Clean up @order annotation in TransactionAspectConfig.

saga-demo/tcc-spring-demo/README.md
=> Update README.md of tcc-spring-demo

saga-demo/tcc-spring-demo/README.md
=> Update the method of simulating a failed scenario for tcc-spring-demo.

saga-demo/tcc-spring-demo/inventory/src/main/java/org/apache/servicecomb/saga/demo/pack/inventory/InventoryService.java
=> Fixed the error when update inventory in tcc-spring-demo.

alpha/alpha-server/src/main/java/org/apache/servicecomb/saga/alpha/server/console/saga/model/Stats.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/saga/alpha/server/console/saga/SagaTransactionsControllerTest.java
=> SCB-995 Add Unit Test for Alpha Console API's

alpha/alpha-core/src/main/java/org/apache/servicecomb/saga/alpha/core/CompositeOmegaCallback.java
=> SCB-1081 current issue when Calling the compensation from CompositeOmegaCallback (#353)

acceptance-tests/acceptance-pack-dubbo-demo/pom.xml, acceptance-tests/acceptance-pack-spring-demo/pom.xml, acceptance-tests/acceptance-pack-tcc-spring-demo/pom.xml, acceptance-tests/pom.xml, alpha/alpha-server/pom.xml, demo/pom.xml, demo/saga-dubbo-demo/pom.xml, integration-tests/pack-tests/pom.xml, omega/omega-spring-tx/pom.xml, persistence/persistence-jpa/pom.xml, pom.xml
=> SCB-1086 Using spring-boot-2 by default

omega/omega-transport/omega-transport-dubbo/src/main/java/org/apache/servicecomb/pack/omega/transport/dubbo/SagaDubboConsumerFilter.java, omega/omega-transport/omega-transport-dubbo/src/main/java/org/apache/servicecomb/pack/omega/transport/dubbo/SagaDubboProviderFilter.java, omega/omega-transport/omega-transport-feign/src/main/java/org/apache/servicecomb/pack/omega/transport/feign/FeignClientRequestInterceptor.java, omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/pack/omega/transport/resttemplate/TransactionClientHttpRequestInterceptor.java, omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/pack/omega/transport/resttemplate/TransactionHandlerInterceptor.java, omega/omega-transport/omega-transport-servicecomb/src/main/java/org/apache/servicecomb/pack/omega/transport/servicecomb/SagaConsumerHandler.java, omega/omega-transport/omega-transport-servicecomb/src/main/java/org/apache/servicecomb/pack/omega/transport/servicecomb/SagaProviderHandler.java
=> SCB-1090 Unified the logger output of the Omega transports.

demo/tcc-spring-demo/inventory/pom.xml
=> SCB-1094 Fixed the java doc build error in tcc-inventory module

LICENSE
=> Update license for pack-web source

demo/pom.xml, distribution/pom.xml, distribution/src/assembly/bin.xml
=> SCB-1097 Clean up pack-distribution module

acceptance-tests/pom.xml, alpha/pom.xml, demo/pom.xml, demo/saga-dubbo-demo/pom.xml, demo/saga-servicecomb-demo/pom.xml, demo/saga-spring-demo/pom.xml, demo/tcc-spring-demo/pom.xml, docker-build-config/pom.xml, integration-tests/pom.xml, omega/pom.xml, pack-common/pom.xml, pack-contracts/pom.xml, persistence/pom.xml, pom.xml, web/pom.xml
Clean up the pom artifacts to fix the build error of demo.
=>  SCB-1098 Update the pom artifacts

omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/pack/omega/transport/resttemplate/TransactionHandlerInterceptor.java
- [ x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[https://github.com/apache/servicecomb-pack/issues/384](https://github.com/apache/servicecomb-pack/issues/384)
- [ x ] Each commit in the pull request should have a meaningful subject line and body.
- [ x ] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
- [ x ] Write a pull request description that is detailed enough to …
=> SCB-1121 Improve TransactionHandlerInterceptor to clean up the OmegaContext

omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/pack/omega/transport/resttemplate/RestTemplateConfig.java
RestTemplate Bean 增加名称 omegaRestTemplate
=> SCB-1122 Add name on Omega related RestTemplateBean

omega/omega-context/src/main/java/org/apache/servicecomb/pack/omega/context/ServiceConfig.java, omega/omega-spring-starter/src/main/java/org/apache/servicecomb/pack/omega/spring/OmegaSpringConfig.java, omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/pack/omega/transport/resttemplate/RestTemplateConfig.java
omega instanceid default value is ${spring.applicatiion.name}-IP
support customs value it's like alpha.instance.instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${server.port}
---
=> SCB-1125 fixed Add omega instanceid to properties

omega/omega-transport/omega-transport-dubbo/src/main/java/org/apache/servicecomb/pack/omega/transport/dubbo/SagaDubboProviderFilter.java, omega/omega-transport/omega-transport-dubbo/src/test/java/org/apache/servicecomb/pack/omega/transport/dubbo/SagaDubboProviderFilterTest.java, omega/omega-transport/omega-transport-servicecomb/src/main/java/org/apache/servicecomb/pack/omega/transport/servicecomb/SagaProviderHandler.java, omega/omega-transport/omega-transport-servicecomb/src/test/java/org/apache/servicecomb/pack/omega/transport/servicecomb/SagaProviderHandlerTest.java
To fix the issue of #384 in other transports.
=> SCB-1121 Clean up the OmegaContext when the invocation is over

demo/saga-servicecomb-demo/scb-booking/src/main/resources/microservice.yaml, demo/saga-servicecomb-demo/scb-car/src/main/resources/microservice.yaml, demo/saga-servicecomb-demo/scb-hotel/src/main/resources/microservice.yaml, omega/omega-transport/omega-transport-dubbo/src/main/java/org/apache/servicecomb/pack/omega/transport/dubbo/PackDubboConsumerFilter.java, omega/omega-transport/omega-transport-dubbo/src/main/java/org/apache/servicecomb/pack/omega/transport/dubbo/PackDubboProviderFilter.java, omega/omega-transport/omega-transport-dubbo/src/main/resources/META-INF/dubbo/com.alibaba.dubbo.rpc.Filter, omega/omega-transport/omega-transport-dubbo/src/test/java/org/apache/servicecomb/pack/omega/transport/dubbo/PackDubboConsumerFilterTest.java, omega/omega-transport/omega-transport-dubbo/src/test/java/org/apache/servicecomb/pack/omega/transport/dubbo/PackDubboProviderFilterTest.java, omega/omega-transport/omega-transport-servicecomb/src/main/java/org/apache/servicecomb/pack/omega/transport/servicecomb/PackConsumerHandler.java, omega/omega-transport/omega-transport-servicecomb/src/main/java/org/apache/servicecomb/pack/omega/transport/servicecomb/PackProviderHandler.java, omega/omega-transport/omega-transport-servicecomb/src/main/resources/config/cse.handler.xml, omega/omega-transport/omega-transport-servicecomb/src/test/java/org/apache/servicecomb/pack/omega/transport/servicecomb/PackConsumerHandlerTest.java, omega/omega-transport/omega-transport-servicecomb/src/test/java/org/apache/servicecomb/pack/omega/transport/servicecomb/PackProviderHandlerTest.java
Rename the SagaHandler -> PackHandler, for the servicecomb java-chassis module we need to update the configuration.
=> SCB-1124 Rename the Transport Handler Name.

acceptance-tests/acceptance-pack-spring-demo/src/test/resources/pack_compensation_scenario.feature, acceptance-tests/acceptance-pack-spring-demo/src/test/resources/pack_post_car_exception_scenario.feature, acceptance-tests/acceptance-pack-spring-demo/src/test/resources/pack_success_scenario.feature, acceptance-tests/acceptance-pack-spring-demo/src/test/resources/pack_timeout_scenario.feature, demo/saga-spring-demo/README.md, demo/saga-spring-demo/car/src/main/java/org/apache/servicecomb/pack/demo/car/CarBooking.java, demo/saga-spring-demo/hotel/src/main/java/org/apache/servicecomb/pack/demo/hotel/HotelBooking.java
=> SCB-1119 Add the order number on the demo

omega/omega-transport/omega-transport-resttemplate/src/main/java/org/apache/servicecomb/pack/omega/transport/resttemplate/TransactionHandlerInterceptor.java
- [ x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes
[https://github.com/apache/servicecomb-pack/issues/384](https://github.com/apache/servicecomb-pack/issues/384)
- [ x ] Each commit in the pull request should have a meaningful subject line and body.
- [ x ] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
- [ x ] Write a pull request description that is detailed enough to …
=> SCB-384 Improve TransactionHandlerInterceptor to clean up the OmegaContext

acceptance-tests/acceptance-pack-cluster-spring-demo/pom.xml, acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/java/org/apache/servicecomb/pack/PackStepdefs.java, acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/java/org/apache/servicecomb/pack/RunCucumberIT.java, acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/alpha_shutdown.btm, acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/booking_exception.btm, acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/booking_timeout.btm, acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/log4j2-test.xml, acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/pack_compensation_scenario.feature, acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/pack_post_car_exception_scenario.feature, acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/pack_success_scenario.feature, acceptance-tests/acceptance-pack-cluster-spring-demo/src/test/resources/pack_timeout_scenario.feature, acceptance-tests/pom.xml, alpha/alpha-core/src/main/java/org/apache/servicecomb/pack/alpha/core/actuate/endpoint/AlphaStatus.java, alpha/alpha-server/pom.xml, alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/cluster/master/ClusterLockService.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/cluster/master/ClusterLockServiceTest.java, alpha/alpha-spring-boot-compatibility/alpha-spring-boot-1-starter/pom.xml, alpha/alpha-spring-boot-compatibility/alpha-spring-boot-1-starter/src/main/java/org/apache/servicecomb/pack/alpha/server/actuate/endpoint/ActuatorEndpoint.java, alpha/alpha-spring-boot-compatibility/alpha-spring-boot-1-starter/src/main/java/org/apache/servicecomb/pack/alpha/server/actuate/endpoint/AlphaEndpoint.java, alpha/alpha-spring-boot-compatibility/alpha-spring-boot-1-starter/src/main/java/org/apache/servicecomb/pack/alpha/server/actuate/endpoint/mvc/ActuatorMvcEndpoint.java, alpha/alpha-spring-boot-compatibility/alpha-spring-boot-2-starter/pom.xml, alpha/alpha-spring-boot-compatibility/alpha-spring-boot-2-starter/src/main/java/org/apache/servicecomb/pack/alpha/server/actuate/endpoint/AlphaEndPoint.java, alpha/alpha-spring-boot-compatibility/pom.xml, demo/saga-spring-demo/booking/src/main/java/org/apache/servicecomb/pack/demo/booking/BookingController.java
1. Copy module acceptance-park-spring-demo and make the following modifications
2. Modify pom.xml to add two alpha server docker nodes
3. Add alpha_shutdown.btm to pack_success_scenario.feature
4. Inject alpha-shutdown.btm into the postCarBooking method of Booking trigger stop alpha master node
=> [SCB-1142] Add acceptance-pack-cluster-spring-demo for alpah cluster 

alpha/alpha-core/src/main/java/org/apache/servicecomb/pack/alpha/core/actuate/endpoint/AlphaStatus.java, alpha/alpha-spring-boot-compatibility/alpha-spring-boot-1-starter/pom.xml, alpha/alpha-spring-boot-compatibility/alpha-spring-boot-1-starter/src/main/java/org/apache/servicecomb/pack/alpha/server/actuate/endpoint/AlphaEndpoint.java, alpha/alpha-spring-boot-compatibility/alpha-spring-boot-2-starter/pom.xml, alpha/alpha-spring-boot-compatibility/alpha-spring-boot-2-starter/src/main/java/org/apache/servicecomb/pack/alpha/server/actuate/endpoint/AlphaEndPoint.java
add License header
changed spring version to property reference
=> [SCB-1160] SCB-1142 additional

docs/user_guide.md, docs/user_guide_zh.md
=> [SCB-1161] Eureka integration english guide

alpha/alpha-server/pom.xml, alpha/alpha-spring-boot-compatibility/alpha-spring-boot-1-starter/pom.xml, alpha/alpha-spring-boot-compatibility/alpha-spring-boot-2-starter/pom.xml, alpha/alpha-spring-boot-compatibility/pom.xml, pom.xml
Just fix the version issue of alpha-spring-boot-starter.
=> SCB-1142 Clean up the alpha-spring-boot-starter

README.md, README_ZH.md, docs/user_guide.md, docs/user_guide_zh.md
=> [SCB-1182] Modify the default activation profile spring-boot-2 in the document

alpha/alpha-server/pom.xml
Just polish the alpha-server pom.xml
=> SCB-1180 Polish the alpha-server pom.xml

docs/user_guide.md, docs/user_guide_zh.md
=> [SCB-1189] Update the Eureka Integration User Guide for PR #420

alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/AlphaConfig.java
=> [SCB-1194] Specify alphaEventBus bean with @Qualifier("alphaEventBus")

alpha/alpha-server/pom.xml, alpha/alpha-server/src/main/resources/application.yaml, alpha/alpha-server/src/main/resources/bootstrap.yaml, alpha/alpha-spring-cloud-starter-consul/pom.xml, alpha/alpha-spring-cloud-starter-consul/src/main/java/org/apache/servicecomb/pack/alpha/server/discovery/consul/AlphaConsulAutoConfiguration.java, alpha/alpha-spring-cloud-starter-consul/src/main/resources/META-INF/spring.factories, alpha/pom.xml, pom.xml
=> [SCB-1199] service discovery with consul

distribution/src/release/LICENSE
=> [WIP] [SCB-1223] Update the license Information

distribution/src/release/LICENSE
Removed the duplicated artifacts.
=> SCB-1223 Polish the LICENSE file

distribution/src/release/LICENSE, distribution/src/release/licenses/LICENSE-bouncycastle, distribution/src/release/licenses/LICENSE-hamcrest, distribution/src/release/licenses/LICENSE-scala, pom.xml
Update the License plugin setting and clean up the License information
=> SCB-1235 Clean up the License information about third party

docs/faq/cn/how_to_use_mysql_as_alpha_backend_database.md, docs/faq/en/how_to_use_mysql_as_alpha_backend_database.md
Modify the directory name libs to plugins in the documentation, avoid confusion with the libs directory in the release package
=> SCB-1241 Modify the directory name libs to plugins in the documentation

README.md
README.md get start section hyper links is wrong
=> fix doc get start hyperlink

docs/user_guide.md, docs/user_guide_zh.md
Saga 0.3.0 upgrade to 0.4.0 changes
Missing alpha.cluster.address configuration instructions
Spring cloud compatibility note
=> SCB-1244 Update the configuration of Pack 0.4.0 in the user guide

omega/omega-context/src/main/java/org/apache/servicecomb/pack/omega/context/OmegaContext.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/TransactionAspect.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/tcc/TccParticipatorAspect.java
issues #459 
Improved exception prompt
=> SCB-1279 add OmegaContext attributes verification on Aspect

docs/user_guide_zh.md
=> change OmeageContext url to docs/user_guide_zh.md

alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/mvcconfig/WebConfiguration.java
Configuration parameter alpha.rest.cors.enabled=true
You can run a script test in the chrome console
```javascript
var xhr = new XMLHttpRequest();
xhr.open('GET','http://0.0.0.0:8090/saga/stats');
xhr.send(null);
xhr.onload = function(e){
var xhr = e.target;
console.log(xhr.responseText);
}
```
=> [SCB-1281] Allows alpha's restful API to be accessed by CORS

docs/user_guide.md, docs/user_guide_zh.md
=> [SCB-1314] support zookeeper doc 

demo/saga-dubbo-demo/docker-compose-alpha.yaml, demo/saga-dubbo-demo/docker-compose-demo.yaml, demo/saga-dubbo-demo/docker-compose.mysql.yaml, demo/saga-dubbo-demo/docker-compose.yaml, demo/saga-servicecomb-demo/docker-compose.yaml, demo/saga-spring-demo/docker-compose-alpha-perf.yaml, demo/saga-spring-demo/docker-compose-alpha.yaml, demo/saga-spring-demo/docker-compose-demo.yaml, demo/saga-spring-demo/docker-compose.mysql.yaml, demo/saga-spring-demo/docker-compose.yaml, demo/tcc-spring-demo/docker-compose-alpha.yaml, demo/tcc-spring-demo/docker-compose-demo.yaml, demo/tcc-spring-demo/docker-compose.mysql.yaml, demo/tcc-spring-demo/docker-compose.yaml, docker-build-config/assembly/assembly.xml, docker-build-config/docker-entrypoint.sh, docker-build-config/pom.xml
---
Upgrade demo's docker-compose files from version 2.1 to 3.0.
Please notice that conditional `depends_on` which is add in 2.1 [\[1\]][1] is removed from 3.0 [\[2\]][2]. So I change the following like below:
```yaml
depends_on:
database:
condition: service_healthy
```
to like this:
```yaml
depends_on:
- database
```
I tested the modified docker-compose file on my machine, that change also works except that there are some retry log like this:
```txt
2019-06-30 02:45:56.059 ERROR 1 --- [ault-executor-2] o.a.s.p.o.c.g.c.ReconnectStreamObserver  : Failed to process grpc coordinate command.
stacks...
2019-06-30 02:45:56.291  INFO 1 --- [pool-2-thread-1] .a.s.p.o.c.g.c.PushBackReconnectRunnable : Retry …
```
=> [SCB-1335] Upgrade docker-compose file to 3.0

docs/user_guide.md, docs/user_guide_zh.md
=> SCB-1355 edit support Nacos Discovery in user_guide

omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/pack/omega/connector/grpc/AlphaClusterDiscovery.java, omega/omega-spring-cloud-nacos-starter/src/main/java/org/apache/servicecomb/pack/omega/spring/cloud/OmegaSpringNacosConfig.java
=> SCB-1356  add NACOS to DiscoveryType

acceptance-tests/acceptance-pack-spring-demo-with-consul/pom.xml, acceptance-tests/acceptance-pack-spring-demo-with-nacos/pom.xml, acceptance-tests/acceptance-pack-spring-demo-with-zookeeper/pom.xml
Fixed consul docker images version 1.5
Fixed nacos docker images version 1.1.0 and wait for log `Completed initialization in`
Fixed zookeeper docker images version 3.5.5 and wait for log `binding to port`
=> SCB-1367 Fixed docker images version & Start log check

NOTICE, distribution/src/release/NOTICE
=> SCB-1377 Fixed a typo of NOTICE file

alpha/alpha-fsm/pom.xml, alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/FsmAutoConfiguration.java, alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/channel/AbstractActorEventChannel.java, alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/channel/RedisActorEventChannel.java, alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/channel/redis/MessagePublisher.java, alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/channel/redis/MessageSerializer.java, alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/channel/redis/RedisMessagePublisher.java, alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/channel/redis/RedisMessageSubscriber.java, alpha/alpha-fsm/src/test/java/org/apache/servicecomb/pack/alpha/fsm/RedisChannelTest.java, alpha/alpha-server/src/main/resources/application.yaml
=> SCB-1374 support fsm redis channel

alpha/alpha-core/src/test/java/org/apache/servicecomb/pack/alpha/core/CompositeOmegaCallbackTest.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/SpringTxEventRepository.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/SpringTxTimeoutRepository.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/console/saga/SagaTransactionsController.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/tcc/service/TccTxEventService.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/console/saga/SagaTransactionsControllerTest.java
=> SCB-1432 change call PageRequest

alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/FsmAutoConfiguration.java
=> [SCB-1439]Optimize class ElasticsearchTransactionRepository persistence parameters

alpha/alpha-fsm-channel-kafka/README.md, alpha/alpha-fsm-channel-kafka/src/main/java/org/apache/servicecomb/pack/alpha/fsm/channel/kafka/KafkaChannelAutoConfiguration.java, alpha/alpha-fsm-channel-kafka/src/main/java/org/apache/servicecomb/pack/alpha/fsm/channel/kafka/KafkaMessagePublisher.java
=> SCB-1442 Topic initialization & Class KafkaMessagePublisher needs to use globalTxId as the partitioning strategy

docs/user_guide.md, docs/user_guide_zh.md
=> [SCB-1425] Docs for @SagaEnd annotation

pom.xml
sub project version can set ${project.version} in parent pom file
=> optimize pom jar version

omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/tcc/TccParticipatorAspect.java
fix tcc client not check alpha response, if response is true,  branch transcation can stop early。
=> fix tcc transcation has been aborded

pom.xml
=> SCB-1535 Remove expired Dependency

omega/omega-transport/omega-transport-feign/pom.xml, pom.xml
This PR should address the issue #577.
=> SCB-1541 Set the dependency of OpenFeign core scope to be provided

.travis.yml, scripts/test.sh
=> [SCB-1595] ServiceComb Pack integrates with SonarCloud

alpha/alpha-benchmark/src/main/java/org/apache/servicecomb/pack/alpha/benchmark/SagaEventBenchmark.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/AlphaEventController.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/api/APIv1Controller.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/console/saga/SagaTransactionsController.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/fsm/FsmSagaDataController.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/tcc/AlphaTccEventController.java
=> SCB-1599  Modify the sonar warning

omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/wrapper/RecoveryPolicyTimeoutWrapper.java
=> [SCB-1614] Polishing code

alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/GrpcTxEventEndpointImpl.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/fsm/GrpcSagaEventService.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/AlphaIntegrationTest.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/AlphaIntegrationWithRandomPortTest.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/fsm/OmegaEventSender.java, omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/pack/omega/connector/grpc/core/ReconnectStreamObserver.java, omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/pack/omega/connector/grpc/saga/GrpcCompensateStreamObserver.java, omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/pack/omega/connector/grpc/saga/GrpcSagaClientMessageSender.java, omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/pack/omega/connector/grpc/saga/SagaLoadBalanceSenderWithTLSTest.java, omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/pack/omega/connector/grpc/saga/SagaLoadBalancedSenderTestBase.java, pack-contracts/pack-contract-grpc/src/main/proto/GrpcTxEvent.proto
This is the first step to Improve the transaction compensation mechanism for FSM
[1] https://issues.apache.org/jira/browse/SCB-1622
=> [SCB-1577] Modify the OnConnected method to bidirectional streaming RPC

alpha/alpha-benchmark/src/main/java/org/apache/servicecomb/pack/alpha/benchmark/SagaEventBenchmark.java, alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/channel/kafka/KafkaChannelAutoConfiguration.java, alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/channel/kafka/KafkaMessagePublisher.java, alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/repository/elasticsearch/ElasticsearchTransactionRepository.java, omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/pack/omega/connector/grpc/core/GrpcOnErrorHandler.java, omega/omega-connector/omega-connector-grpc/src/main/java/org/apache/servicecomb/pack/omega/connector/grpc/saga/RetryableMessageSender.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/wrapper/RecoveryPolicyTimeoutWrapper.java
=> SCB-1604 modify InterruptedException

integration-tests/coverage-aggregate/pom.xml, integration-tests/explicit-transaction-context-tests/pom.xml, integration-tests/explicit-transaction-context-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/explicitcontext/CommandEnvelopeRepository.java, integration-tests/explicit-transaction-context-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/explicitcontext/ExplicitTransactionContextIT.java, integration-tests/explicit-transaction-context-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/explicitcontext/GreetingApplication.java, integration-tests/explicit-transaction-context-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/explicitcontext/GreetingController.java, integration-tests/explicit-transaction-context-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/explicitcontext/GreetingService.java, integration-tests/explicit-transaction-context-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/explicitcontext/TransactionContextDto.java, integration-tests/explicit-transaction-context-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/explicitcontext/TxEventEnvelopeRepository.java, integration-tests/explicit-transaction-context-tests/src/test/resources/application.yaml, integration-tests/explicit-transaction-context-tests/src/test/resources/log4j2.xml, integration-tests/pack-tests/pom.xml, integration-tests/pack-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/resttemplate/CommandEnvelopeRepository.java, integration-tests/pack-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/resttemplate/GreetingApplication.java, integration-tests/pack-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/resttemplate/GreetingController.java, integration-tests/pack-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/resttemplate/GreetingService.java, integration-tests/pack-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/resttemplate/PackIT.java, integration-tests/pack-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/resttemplate/TxEventEnvelopeRepository.java, integration-tests/pom.xml, omega/omega-context/src/main/java/org/apache/servicecomb/pack/omega/context/TransactionContext.java
---
1. make TransactionContext serializable
1. refactor pack-tests name because it's a IT for RestTemplate scenario
1. Add an IT for explicit TransactionContext transfer
=> SCB-1670 TransactionContext should be serializable

alpha/alpha-ui/src/main/java/org/apache/servicecomb/pack/alpha/ui/controller/TransactionController.java
sun.misc.BASE64Decoder not available on Java 9
=> [SCB-1668] Replace sun.misc.BASE64* with java.util.Base64

alpha/alpha-ui/src/main/resources/templates/error.html
Added prompt "Alpha UI only supports state machine mode" on the error page
=> [SCB-1688] Added prompt information when visit Alpha UI in non-FSM

docs/upgrade_guide/0.6.0-upgrade-guide.md, docs/upgrade_guide/0.6.0-upgrade-guide_zh.md, docs/user_guide.md, docs/user_guide_zh.md, integration-tests/explicit-transaction-context-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/explicitcontext/GreetingService.java, integration-tests/pack-tests/src/test/java/org/apache/servicecomb/pack/integration/tests/resttemplate/GreetingService.java, omega/omega-spring-tx/src/main/java/org/apache/servicecomb/pack/omega/transaction/spring/CompensableMethodCheckingCallback.java, omega/omega-spring-tx/src/test/java/org/apache/servicecomb/pack/omega/transaction/spring/CompensableAnnotationCheckingTest.java, omega/omega-spring-tx/src/test/java/org/apache/servicecomb/pack/omega/transaction/spring/MisconfiguredRetriesService.java, omega/omega-spring-tx/src/test/java/org/apache/servicecomb/pack/omega/transaction/spring/TransactionalUserService.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/AbstractRecoveryPolicy.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/DefaultRecovery.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/ForwardRecovery.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/TransactionAspect.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/annotations/Compensable.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/wrapper/RecoveryPolicyTimeoutWrapper.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/pack/omega/transaction/DefaultRecoveryTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/pack/omega/transaction/ForwardRecoveryTest.java, omega/omega-transaction/src/test/java/org/apache/servicecomb/pack/omega/transaction/TransactionAspectTest.java
Rename @Compensable property retries and timeout with the "forward" prefix
=> [SCB-1646] Add "forward" prefix to @Compensable property retries and timeout

alpha/alpha-core/src/main/java/org/apache/servicecomb/pack/alpha/core/api/APIv1.java, alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/api/APIv1Impl.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/api/APIv1ControllerTest.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/api/APIv1ControllerTests.java
Improve unit test coverage
Rename file APIv1ControllerTests.java name suffix to ** Test.java for maven-surefire-plugin trigger unit test
=> [SCB-1694] Improve unit test coverages for APIv1Controller

alpha/alpha-core/src/main/java/org/apache/servicecomb/pack/alpha/core/fsm/event/internal/CompensateAckTimeoutEvent.java, alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/SagaActor.java, alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/domain/UpdateTxEventDomain.java, alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/spring/integration/akka/SpringAkkaExtension.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/fsm/AlphaIntegrationFsmTest.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/fsm/OmegaEventSagaSimulator.java, alpha/alpha-ui/src/main/java/org/apache/servicecomb/pack/alpha/ui/controller/TransactionController.java, alpha/alpha-ui/src/main/resources/templates/transaction_details.html, docs/fsm/plantuml/saga-state-diagram.puml, pack-common/src/main/java/org/apache/servicecomb/pack/common/EventType.java
Use property reverseTimeout of @Compensable  to set the timeout of the compensation method
=> [SCB-1735] Support Alpha call compensation timeout strategy

alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/SagaActor.java, omega/omega-transaction/src/main/java/org/apache/servicecomb/pack/omega/transaction/TxEvent.java, pack-common/pom.xml, pack-common/src/main/java/org/apache/servicecomb/pack/common/Environment.java
Configure PAYLOADS_MAX_LENGTH parameter from os environment variables
=> [SCB-1811] Configure PAYLOADS_MAX_LENGTH parameter from os environment

alpha/alpha-fsm/src/main/java/org/apache/servicecomb/pack/alpha/fsm/repository/elasticsearch/ElasticsearchTransactionRepository.java, alpha/alpha-ui/pom.xml, alpha/alpha-ui/src/main/resources/static/js/alpha-transaction.js, alpha/alpha-ui/src/main/resources/templates/fragments/main_layout.html, alpha/alpha-ui/src/main/resources/templates/fragments/transaction_table.html, distribution/src/release/LICENSE, distribution/src/release/licenses/LICENSE-moment
ElasticsearchTemplate.prepareScroll() does not add sorting https://jira.spring.io/browse/DATAES-457
1. Use elasticsearch native client instead of ElasticsearchTemplate
2. Saga list GUI show global transaction start time column
=> SCB-1877 Fixed AlphaUI's Saga list sorted by time bug

alpha/alpha-server/src/main/java/org/apache/servicecomb/pack/alpha/server/AlphaConfig.java, alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/fsm/AlphaIntegrationFsmTest.java
=> SCB-1879 Support to disable the TCC feature from configuration

omega/omega-context/src/main/java/org/apache/servicecomb/pack/omega/context/ServiceConfig.java
=> [SCB-1495] Verify the instanceId size

pack-common/src/main/java/org/apache/servicecomb/pack/common/Environment.java
=> SCB-2044 Fixed the Environment class instance thread issue

demo/tcc-spring-demo/README.md
the server port in the command line in the tcc demo is wrong. 
```
Inventory: 8081
Payment:8082
```
=> fix bug in tcc demo doc

acceptance-tests/acceptance-pack-tcc-spring-demo/src/test/java/org/apache/servicecomb/pack/PackStepdefs.java
Disable the events order check in the TCC acceptance test.
=> SCB-2201 Fixed the acceptance test occasionally fails in CI

scripts/test.sh
Sonarcloud.io nonsupport JDK1.8 after 1 February 2021
=> [SCB-2203] Remove SonarScanner

.github/workflows/asf-snapshots-deploy.yml
Infra ticket https://issues.apache.org/jira/browse/INFRA-21587
=> [SCB-2219] Use Github secrets to configure snapshot deploy to Nexus authentication

.github/workflows/asf-snapshots-deploy.yml
Suggestions[1] from infra 
[1]https://issues.apache.org/jira/browse/INFRA-21587?focusedCommentId=17303898&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17303898https://issues.apache.org/jira/browse/INFRA-21587?focusedCommentId=17303898&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17303898
=> [SCB-2223] Fix the name of NEXUS secrets

alpha/alpha-ui/src/main/java/org/apache/servicecomb/pack/alpha/ui/controller/IndexController.java
System information was not inited when accessing the `http://localhost:8090/` address
resolved #690 #683
=> [SCB-2227] Alpha UI @GetMapping to map "/" request path

alpha/alpha-server/src/test/java/org/apache/servicecomb/pack/alpha/server/fsm/AlphaIntegrationFsmTest.java, omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/pack/omega/connector/grpc/saga/SagaLoadBalancedSenderTest.java
Fix unstable test cases on poor performance CI
These tests case has a probability of timeout errors on poor performance CI,  Here are some failure logs:
https://github.com/apache/servicecomb-pack/runs/2127211795?check_suite_focus=true#step:6:1074
https://github.com/apache/servicecomb-pack/runs/2157935390?check_suite_focus=true#step:6:1995
=> [SCB-2222] Increase waiting time for poor performance CI

.github/workflows/asf-snapshots-deploy.yml, .github/workflows/master-pr-build.yaml, .github/workflows/master-push-build.yaml, omega/omega-transport/omega-transport-hystrix/pom.xml, pack-contracts/pack-contract-grpc/pom.xml, pom.xml
Just source compatibility java 11
=> [SCB-2239] Compatibility Java 11

pom.xml
=> SCB-2390 Upgrade grpc and netty to Support the Mac M1

alpha/alpha-spec-saga-akka/src/test/java/org/apache/servicecomb/pack/alpha/spec/saga/akka/it/SagaIntegrationTest.java, omega/omega-connector/omega-connector-grpc/src/test/java/org/apache/servicecomb/pack/omega/connector/grpc/saga/SagaLoadBalancedSenderTest.java, pom.xml
Related https://github.com/apache/servicecomb-pack/issues/763
=> SCB-2641 Add flatten-maven-plugin for update version placeholders ${revision} for main pom

alpha/alpha-spec-saga-akka/src/test/java/org/apache/servicecomb/pack/alpha/spec/saga/akka/it/SagaIntegrationTest.java, demo/saga-dubbo-demo/service-api/pom.xml, demo/saga-dubbo-demo/serviceb/pom.xml, demo/saga-dubbo-demo/servicec/pom.xml, integration-tests/coverage-aggregate/pom.xml, pom.xml
Related https://github.com/apache/servicecomb-pack/issues/763
=> SCB-2641 Fix wrong version placeholder

.github/workflows/master-pr-build.yaml, demo/saga-dubbo-demo/service-api/pom.xml, demo/saga-dubbo-demo/serviceb/pom.xml, demo/saga-dubbo-demo/servicec/pom.xml, integration-tests/coverage-aggregate/pom.xml, pom.xml
Related https://github.com/apache/servicecomb-pack/issues/763
=> SCB-2657 Fix wrong version placeholder for branch 0.7.x
